taiga-family/maskito

package.json
projects/core/src/lib/classes/mask-model/mask-model.ts
projects/core/src/lib/classes/mask-model/utils/add-fixed-mask-characters.ts
projects/core/src/lib/classes/mask-model/utils/remove-fixed-mask-characters.ts
projects/core/src/lib/mask.ts
projects/core/src/lib/types/element-state.ts
projects/core/src/lib/types/index.ts

```ts
export interface ElementState {
value: string;
selection: [from: number, to: number];
}
```

refactor(core): introduce concept `ElementState` + replace `caret` with `selection`

---

projects/core/src/lib/classes/mask-model/utils/add-fixed-mask-characters.ts
projects/core/src/lib/classes/mask-model/utils/remove-fixed-mask-characters.ts
projects/demo-integrations/cypress/tests/sandbox/input-phone.cy.ts

https://github.com/Tinkoff/maskito/blob/d03134c160f8a4e6d1cc85d6130b5ca8f0924410/projects/demo-integrations/cypress/tests/sandbox/input-phone.cy.ts#L279-L307

fix(core): incorrect caret position (case with range selection + new key)

---

projects/core/src/lib/classes/mask-model/mask-model.ts
projects/core/src/lib/classes/mask-model/utils/add-fixed-mask-characters.ts
projects/demo-integrations/cypress/tests/sandbox/input-phone.cy.ts

fix(core): show fixed character only if there are other not-fixed characters after it

---

projects/core/src/lib/classes/mask-model/mask-model.ts
projects/core/src/lib/classes/mask-model/utils/remove-fixed-mask-characters.ts
projects/core/src/lib/mask.ts
projects/core/src/lib/types/element-state.ts
projects/core/src/lib/types/index.ts
projects/core/src/lib/types/range.ts
projects/core/src/lib/types/selection-range.ts
projects/demo-integrations/cypress/tests/sandbox/input-phone.cy.ts

feat(core): add `Delete`-key support

---

.gitignore
projects/demo/project.json
projects/demo/src/app/modules/sandbox/sandbox.style.less
projects/demo/src/app/modules/sandbox/sandbox.template.html

ci: new `nx serve-ssl` and `nx serve-ip` commands

---

commitlint.config.js
projects/core/src/lib/classes/mask-model/mask-model.ts
projects/core/src/lib/classes/mask-model/utils/add-fixed-mask-characters.ts
projects/core/src/lib/classes/mask-model/utils/calibrate-value-by-mask.ts
projects/core/src/lib/classes/mask-model/utils/get-leading-fixed-characters.ts
projects/core/src/lib/classes/mask-model/utils/guess-valid-value-by-pattern.ts
projects/core/src/lib/classes/mask-model/utils/guess-valid-value-by-reg-exp.ts
projects/core/src/lib/mask.ts
projects/core/src/lib/utils/extend-to-not-empty-range.ts
projects/core/src/lib/utils/index.ts

Closes #11
Closes #12
https://user-images.githubusercontent.com/35179038/204295602-07ee0387-4916-431b-8dc7-6cb4a24f304c.mov
https://user-images.githubusercontent.com/35179038/204296430-70dac6fe-7d74-4fdb-9015-c882b942e300.mov
https://user-images.githubusercontent.com/35179038/204294871-ffcecea9-9b92-476a-8269-9a283a615df1.mov
https://user-images.githubusercontent.com/35179038/204295143-082da86c-9a20-475b-b483-617fc7c22059.mov

feat(core): try guess value when autofill/paste/drop contains invalid characters

---

projects/core/src/lib/classes/index.ts
projects/core/src/lib/classes/mask-history.ts
projects/core/src/lib/mask.ts
projects/demo-integrations/cypress/tests/sandbox/input-phone.cy.ts

Closes #2
Partial support of undo/redo commands.

feat(core): new `MaskHistory` class (undo/redo partial support)

---

projects/core/src/lib/mask.ts
projects/core/src/lib/types/typed-input-event.ts
projects/demo-integrations/cypress/tests/sandbox/text-area.cy.ts
projects/demo/src/app/modules/sandbox/masks.ts
projects/demo/src/app/modules/sandbox/sandbox.template.html

fix(core): line-break support for `TextArea`

---

angular.json
projects/kit/README.md
projects/kit/jest.config.js
projects/kit/package.json
projects/kit/project.json
projects/kit/src/index.ts
projects/kit/src/lib/kit.ts
projects/kit/tsconfig.json
projects/kit/tsconfig.lib.json
projects/kit/tsconfig.spec.json
tsconfig.base.json

All files are generated via `nx g @nrwl/js:library kit`-command

feat(kit): create new library (run `nx g @nrwl/js:library kit`)

---

.github/workflows/deploy-preview.yml
.github/workflows/e2e.yml
projects/core/src/lib/mask.ts
projects/demo/src/app/app.server.module.ts
projects/demo/src/app/server-error-handler.ts

ci: fail Github-job with Cypress tests on SSR error

---

.github/workflows/deploy.yml

ci: fix `nx: command not found`

---

projects/core/src/lib/mask.ts
projects/core/src/lib/types/mask-processors.ts
projects/core/src/lib/utils/element-states-equality.ts
projects/core/src/lib/utils/pipe.ts
projects/core/src/lib/utils/test/pipe.spec.ts
projects/kit/src/lib/time/processors/zero-placeholders-preprocessor.ts

Fix review comments: https://github.com/Tinkoff/maskito/pull/28

feat(core): standardize pre- and postprocessors (separate mutable data from readonly)

---

projects/angular/src/lib/maskito.directive.ts
projects/core/src/lib/classes/mask-history.ts
projects/core/src/lib/mask.ts
projects/demo-integrations/cypress/tests/angular/form-control-changes.cy.ts

fix(angular): no `FormControl` changes

---

projects/core/src/lib/classes/mask-model/utils/apply-overwrite-mode.ts
projects/core/src/lib/types/mask-options.ts
projects/demo-integrations/cypress/tests/kit/number/decimal-zero-padding.cy.ts
projects/demo-integrations/cypress/tests/kit/number/number-basic.cy.ts
projects/demo-integrations/cypress/tests/kit/number/number-precision.cy.ts
projects/demo-integrations/cypress/tests/kit/number/number-thousand-separator.cy.ts
projects/demo-integrations/cypress/tests/kit/number/number-zero-integer-part.cy.ts
projects/demo-integrations/cypress/tests/kit/number/utils.ts
projects/demo/src/app/app.routes.ts
projects/demo/src/pages/kit/number/number-mask-doc.component.ts
projects/demo/src/pages/kit/number/number-mask-doc.module.ts
projects/demo/src/pages/kit/number/number-mask-doc.template.html
projects/demo/src/pages/kit/template/kit-template-doc.component.ts
projects/demo/src/pages/kit/template/kit-template-doc.module.ts
projects/demo/src/pages/kit/template/kit-template-doc.template.html
projects/demo/src/pages/pages.ts
projects/kit/src/index.ts
projects/kit/src/lib/number/index.ts
projects/kit/src/lib/number/number-mask.ts
projects/kit/src/lib/number/processors/decimal-zero-padding-postprocessor.ts
projects/kit/src/lib/number/processors/index.ts
projects/kit/src/lib/number/processors/leading-zeroes-validation-postprocessor.ts
projects/kit/src/lib/number/processors/not-empty-integer-part-preprocessor.ts
projects/kit/src/lib/number/processors/preudo-separators-preprocessor.ts
projects/kit/src/lib/number/processors/separator-deletion-preprocessor.ts
projects/kit/src/lib/number/processors/thousand-separator-postprocessor.ts
projects/kit/src/lib/number/utils/generate-mask-expression.ts
projects/kit/src/lib/number/utils/index.ts

feat(kit): new `Number`-mask

---

package-lock.json
package.json
projects/demo/project.json
projects/demo/src/app/app.providers.ts
projects/demo/src/typings.d.ts
projects/demo/tsconfig.app.json
projects/demo/tsconfig.json
projects/demo/tsconfig.server.json
projects/demo/webpack.config.ts

https://webpack.js.org/guides/asset-modules/
```ts
import('./time-mask-doc.module.ts?raw')
```

ci: add Webpack 5 asset modules (to load raw file content)

---

.github/workflows/e2e.yml
package-lock.json
package.json

fix(demo): `npm run build:prerender` throws `NullInjectorError`

---

projects/demo-integrations/cypress/tests/sandbox/input-phone.cy.ts
projects/demo-integrations/cypress/tests/sandbox/text-area.cy.ts
projects/demo/src/app/app.routes.ts
projects/demo/src/app/app.style.less
projects/demo/src/pages/documentation/core-concepts-overview/core-concepts-overview.component.ts
projects/demo/src/pages/documentation/core-concepts-overview/core-concepts-overview.module.ts
projects/demo/src/pages/documentation/core-concepts-overview/core-concepts-overview.styles.less
projects/demo/src/pages/documentation/core-concepts-overview/core-concepts-overview.template.html
projects/demo/src/pages/documentation/core-concepts-overview/examples/maskito-public-api-demo.md
projects/demo/src/pages/documentation/maskito-libraries/maskito-libraries.component.ts
projects/demo/src/pages/documentation/maskito-libraries/maskito-libraries.module.ts
projects/demo/src/pages/documentation/maskito-libraries/maskito-libraries.template.html
projects/demo/src/pages/documentation/what-is-maskito/what-is-maskito.component.ts
projects/demo/src/pages/documentation/what-is-maskito/what-is-maskito.module.ts
projects/demo/src/pages/documentation/what-is-maskito/what-is-maskito.style.less
projects/demo/src/pages/documentation/what-is-maskito/what-is-maskito.template.html
projects/demo/src/pages/pages.ts
projects/demo/src/styles.css

chore(demo): new documentation pages

---

projects/demo-integrations/cypress/tests/angular/form-control-changes.cy.ts
projects/demo-integrations/cypress/tests/kit/number/utils.ts
projects/demo-integrations/cypress/tests/kit/time/time-basic.cy.ts
projects/demo-integrations/cypress/tests/kit/time/time-mode.cy.ts
projects/demo-integrations/cypress/tests/sandbox/input-phone.cy.ts
projects/demo-integrations/cypress/tests/sandbox/text-area.cy.ts
projects/demo-integrations/cypress/tests/ssr/ssr.cy.ts
projects/demo/src/app/app.routes.ts
projects/demo/src/pages/documentation/core-concepts-overview/core-concepts-overview.component.ts
projects/demo/src/pages/documentation/core-concepts-overview/core-concepts-overview.module.ts
projects/demo/src/pages/documentation/core-concepts-overview/core-concepts-overview.template.html
projects/demo/src/pages/documentation/core-concepts-overview/examples/maskito-public-api-demo.md
projects/demo/src/pages/documentation/mask-expression/examples/basic-time-example.md
projects/demo/src/pages/documentation/mask-expression/examples/dynamic-mask-expression-demo.md
projects/demo/src/pages/documentation/mask-expression/examples/reg-exp-mask-expression-demo.md
projects/demo/src/pages/documentation/mask-expression/mask-expression.component.ts
projects/demo/src/pages/documentation/mask-expression/mask-expression.module.ts
projects/demo/src/pages/documentation/mask-expression/mask-expression.template.html
projects/demo/src/pages/documentation/maskito-libraries/maskito-libraries.component.ts
projects/demo/src/pages/documentation/what-is-maskito/what-is-maskito.component.ts
projects/demo/src/pages/pages.ts
tsconfig.base.json

chore(demo): new documentation page `Mask expression`

---

.eslintrc.js
projects/demo/src/pages/documentation/maskito-libraries/maskito-libraries.template.html

```
/maskito/projects/demo/src/pages/documentation/maskito-libraries/maskito-libraries.template.html
0:0  error  Parsing error:
ESLint was configured to run on `<...>/maskito-libraries.template.html` using
`parserOptions.project` <...>/tsconfig.eslint.json
The extension for the file (`.html`) is non-standard.
You should add `parserOptions.extraFileExtensions` to your config
```

ci: fix eslint error `The extension for the file (.html) is non-standard`

---

projects/demo/src/pages/documentation/processors/examples/maskito-pipe-demo.md
projects/demo/src/pages/documentation/processors/processors.component.ts
projects/demo/src/pages/documentation/processors/processors.template.html
projects/demo/src/pages/pages.ts

chore(demo): add `maskitoPipe`-section to `Processors`-page

---

projects/demo/src/app/app.routes.ts
projects/demo/src/pages/documentation/core-concepts-overview/core-concepts-overview.component.ts
projects/demo/src/pages/documentation/core-concepts-overview/core-concepts-overview.module.ts
projects/demo/src/pages/documentation/core-concepts-overview/core-concepts-overview.template.html
projects/demo/src/pages/documentation/core-concepts-overview/examples/maskito-public-api-demo.md
projects/demo/src/pages/documentation/mask-expression/mask-expression.component.ts
projects/demo/src/pages/documentation/mask-expression/mask-expression.template.html
projects/demo/src/pages/documentation/overwrite-mode/examples/dynamic/component.ts
projects/demo/src/pages/documentation/overwrite-mode/examples/dynamic/mask.ts
projects/demo/src/pages/documentation/overwrite-mode/examples/replace/component.ts
projects/demo/src/pages/documentation/overwrite-mode/examples/replace/mask.ts
projects/demo/src/pages/documentation/overwrite-mode/examples/shift/component.ts
projects/demo/src/pages/documentation/overwrite-mode/examples/shift/mask.ts
projects/demo/src/pages/documentation/overwrite-mode/overwrite-mode.component.ts
projects/demo/src/pages/documentation/overwrite-mode/overwrite-mode.module.ts
projects/demo/src/pages/documentation/overwrite-mode/overwrite-mode.template.html
projects/demo/src/pages/documentation/processors/processors.component.ts
projects/demo/src/pages/documentation/processors/processors.template.html
projects/demo/src/pages/pages.ts

chore(demo): new documentation page `Overwrite mode`

---

projects/demo-integrations/cypress/tests/kit/number/number-decimal-zero-padding.cy.ts
projects/kit/src/lib/masks/number/processors/decimal-zero-padding-postprocessor.ts

fix(kit): `Number` ignores `decimalZeroPadding: true` if integer part is deleted

---

projects/demo-integrations/cypress/tests/kit/date/date-min-max.cy.ts
projects/demo-integrations/cypress/tests/kit/date/date-mode.cy.ts
projects/demo-integrations/cypress/tests/kit/date/date-separator.cy.ts
projects/demo/src/pages/kit/date/date-mask-doc.component.ts
projects/demo/src/pages/kit/date/date-mask-doc.template.html
projects/kit/src/lib/masks/date/date-mask.ts
projects/kit/src/lib/masks/date/processors/index.ts
projects/kit/src/lib/masks/date/processors/min-max-postprocessor.ts
projects/kit/src/lib/masks/date/utils/date-to-segments.ts
projects/kit/src/lib/masks/date/utils/index.ts
projects/kit/src/lib/masks/date/utils/segments-to-date.ts

feat(kit): `DateMask` add max/min options

---

projects/demo/src/pages/kit/number/examples/4-dynamic-decimal-zero-padding/component.ts
projects/demo/src/pages/kit/number/examples/4-dynamic-decimal-zero-padding/mask.ts
projects/demo/src/pages/kit/number/number-mask-doc.component.ts
projects/demo/src/pages/kit/number/number-mask-doc.module.ts
projects/demo/src/pages/kit/number/number-mask-doc.template.html

chore(demo): `Number` add example with dynamically configurable `decimalZeroPadding`

---

projects/angular/package.json
projects/angular/src/index.ts
projects/angular/src/lib/maskito-options.directive.ts
projects/angular/src/lib/maskito-options.ts
projects/angular/src/lib/maskito.directive.ts
projects/angular/src/lib/maskito.module.ts
projects/demo-integrations/cypress/tests/angular/di-approach.cy.ts
projects/demo/src/app/modules/sandbox/sandbox.component.ts
projects/demo/src/app/modules/sandbox/sandbox.template.html
projects/demo/src/pages/kit/time/time-mask-doc.template.html

feat(angular): improve DI-approach

---

projects/demo/src/app/app.routes.ts

1. Open any long documentation page (e.g., https://tinkoff.github.io/maskito/core-concepts/processors)
2. Scroll to the end of the page
3. Press link to another documentation page
https://user-images.githubusercontent.com/35179038/214326914-0a4b7996-0d57-4b5a-95aa-2b71ec948eaf.mov
https://user-images.githubusercontent.com/35179038/214326747-09331bf8-d54b-4226-b1cf-42858368e316.mov

chore(demo): fix scroll position on page navigation

---

projects/demo-integrations/cypress/tests/kit/date-range/date-range-basic.cy.ts

chore(demo-integrations): `DateRange` more cypress tests

---

projects/demo-integrations/cypress/tests/kit/date-range/date-range-basic.cy.ts
projects/demo-integrations/cypress/tests/kit/date-range/date-range-mode.cy.ts
projects/demo-integrations/cypress/tests/kit/date/date-basic.cy.ts
projects/demo-integrations/cypress/tests/kit/date/date-min-max.cy.ts
projects/demo-integrations/cypress/tests/kit/date/date-mode.cy.ts
projects/demo-integrations/cypress/tests/recipes/card/card.cy.ts
projects/demo/src/app/app.routes.ts
projects/demo/src/pages/kit/date-range/date-range-mask-doc.component.ts
projects/demo/src/pages/kit/date/date-mask-doc.component.ts
projects/demo/src/pages/pages.ts
projects/demo/src/pages/recipes/card/card-doc.component.ts
projects/demo/src/pages/recipes/card/card-doc.module.ts
projects/demo/src/pages/recipes/card/card-doc.template.html
projects/demo/src/pages/recipes/card/examples/1-basic/component.ts
projects/demo/src/pages/recipes/card/examples/1-basic/style.less
projects/demo/src/pages/recipes/card/examples/1-basic/template.html
projects/kit/src/lib/constants/date-segment-value-length.ts
projects/kit/src/lib/constants/index.ts
projects/kit/src/lib/masks/date-range/date-range-mask.ts
projects/kit/src/lib/masks/date/date-mask.ts
projects/kit/src/lib/masks/date/utils/date-segment-value-length.ts
projects/kit/src/lib/masks/date/utils/index.ts
projects/kit/src/lib/masks/date/utils/segments-to-date.ts
projects/kit/src/lib/types/date-mode.ts
projects/kit/src/lib/utils/date-segment-value-length.ts
projects/kit/src/lib/utils/get-date-mode-template.ts
projects/kit/src/lib/utils/index.ts
projects/kit/src/lib/utils/parse-date-string.ts
projects/kit/src/lib/utils/to-date-string.ts
projects/kit/src/lib/utils/validate-date-string.ts

feat(kit): `Date` mask support `mm/yy` mode, add `Card` recipe

---

projects/demo/src/app/app.providers.ts
projects/demo/src/pages/recipes/card/card-doc.module.ts
projects/demo/src/pages/recipes/card/card-doc.template.html

chore(demo): update `TUI_DOC_SOURCE_CODE` (drop links for recipes)

---

projects/angular/project.json
projects/kit/project.json

Delete `/dist`-folder and run `nx build kit`
It throws error:
```
Some of the project kit's dependencies have not been built yet. Please build these libraries before:
- core
```
Running target build for project `kit` and 1 task(s) that it depends on.

ci: configure nx-`dependsOn` of `kit` & `angular` packages

---

projects/demo-integrations/cypress/tests/kit/date-range/date-range-min-max-length.cy.ts
projects/demo-integrations/cypress/tests/kit/date-range/date-range-min-max.cy.ts
projects/demo/src/pages/kit/date-range/date-range-mask-doc.component.ts
projects/demo/src/pages/kit/date-range/date-range-mask-doc.template.html
projects/kit/src/index.ts
projects/kit/src/lib/constants/default-min-max-dates.ts
projects/kit/src/lib/constants/index.ts
projects/kit/src/lib/masks/date-range/date-range-mask.ts
projects/kit/src/lib/masks/date-range/min-max-range-length-postprocessor.ts
projects/kit/src/lib/processors/min-max-date-postprocessor.ts
projects/kit/src/lib/utils/date/append-date.ts
projects/kit/src/lib/utils/index.ts
projects/kit/src/lib/utils/is-empty.ts

**Partially** solves https://github.com/Tinkoff/maskito/issues/75

feat(kit): `DateRange` add `minLength` / `maxLength` options

---

projects/demo/src/pages/kit/date-range/date-range-mask-doc.component.ts
projects/demo/src/pages/kit/date-range/date-range-mask-doc.module.ts
projects/demo/src/pages/kit/date-range/date-range-mask-doc.template.html
projects/demo/src/pages/kit/date-range/examples/1-date-localization/component.ts
projects/demo/src/pages/kit/date-range/examples/1-date-localization/mask.ts
projects/demo/src/pages/kit/date-range/examples/2-min-max/component.ts
projects/demo/src/pages/kit/date-range/examples/2-min-max/mask.ts
projects/demo/src/pages/kit/date-range/examples/3-min-max-length/component.ts
projects/demo/src/pages/kit/date-range/examples/3-min-max-length/mask.ts

chore(demo): `DateRange` add examples to documentation page

---

.github/workflows/test.yml
projects/angular/jest.config.js
projects/angular/project.json
projects/core/jest.config.js
projects/core/project.json
projects/demo/jest.config.js
projects/demo/project.json
projects/kit/jest.config.js
projects/kit/project.json

Every new opened PR triggers tests from `demo`-project only.
Every new opened PR triggers tests all projects.

ci: run all tests on PR

---

projects/demo/src/pages/kit/date-range/examples/1-date-localization/component.ts

chore(demo): `DateRange` example throws `RangeError: Invalid time value`

---

projects/demo-integrations/cypress/tests/kit/date-range/date-range-separator.cy.ts
projects/demo-integrations/cypress/tests/kit/date/date-separator.cy.ts
projects/kit/src/lib/constants/index.ts
projects/kit/src/lib/constants/possible-dates-separator.ts
projects/kit/src/lib/constants/unicode-characters.ts
projects/kit/src/lib/processors/min-max-date-postprocessor.ts
projects/kit/src/lib/processors/valid-date-preprocessor.ts

fix(kit): accept dates and segments separator as valid input

---

projects/demo/src/pages/kit/date/date-mask-doc.module.ts
projects/demo/src/pages/kit/date/date-mask-doc.template.html

chore(demo): `Date` update documentation page

---

jest.preset.js
projects/angular/jest.config.js
projects/core/jest.config.js
projects/kit/jest.config.js
tsconfig.base.json

Run unit tests via Webstorm button
It fails with error
```
File not found: tsconfig.spec.json (resolved as: /Users/n.barsukov/WebstormProjects/maskito/projects/core/tsconfig.spec.json)
```
No error

chore: fix broken IDE run of jest tests

---

projects/demo/src/pages/kit/time/examples/1-modes/component.ts
projects/demo/src/pages/kit/time/examples/1-modes/mask.ts
projects/demo/src/pages/kit/time/examples/2-twelve-hour-format/component.ts
projects/demo/src/pages/kit/time/examples/2-twelve-hour-format/mask.ts
projects/demo/src/pages/kit/time/time-mask-doc.component.ts
projects/demo/src/pages/kit/time/time-mask-doc.module.ts
projects/demo/src/pages/kit/time/time-mask-doc.template.html

chore(demo): `Time` update documentation page

---

projects/core/src/lib/classes/mask-model/mask-model.ts
projects/core/src/lib/classes/mask-model/tests/mask-model-fixed-characters.spec.ts
projects/core/src/lib/classes/mask-model/utils/calibrate-value-by-mask.ts
projects/core/src/lib/classes/mask-model/utils/get-leading-fixed-characters.ts
projects/core/src/lib/classes/mask-model/utils/guess-valid-value-by-pattern.ts
projects/demo-integrations/cypress/tests/recipes/phone/phone.cy.ts
projects/demo/src/pages/kit/time/time-mask-doc.template.html

fix(core): `MaskModel` rejects new character if it is equal to the previous fixed character

---

projects/demo/src/pages/kit/time/examples/2-twelve-hour-format/component.ts

chore(demo): `Time` improve example `12-hours format`

---

CODE_OF_CONDUCT.md
package.json
projects/angular/package.json
projects/core/package.json
projects/kit/package.json

chore: update metadata in `package.json`

---

.github/workflows/build.yml
README.md
projects/demo/src/pages/documentation/what-is-maskito/what-is-maskito.template.html

chore: update root `README.md`

---

projects/angular/README.md
projects/core/README.md
projects/kit/README.md

chore: update `README.md`-files for all packages

---

.github/workflows/create-release.yml
.github/workflows/npm-publish.yml
package.json
projects/angular/package.json
projects/angular/project.json
projects/core/package.json
projects/core/project.json
projects/kit/package.json
projects/kit/project.json

ci: automate package publishing to `npm`

---

.gitignore
projects/angular/project.json
projects/core/project.json
projects/kit/project.json

See https://github.com/Tinkoff/maskito/pull/118

ci: fix automated package publishing fails

---

.github/workflows/build.yml
.github/workflows/deploy-preview.yml
.github/workflows/e2e.yml
.github/workflows/test.yml

ci: skip some workflows for `release`-branches

---

.github/workflows/build.yml
.github/workflows/deploy-preview.yml
.github/workflows/e2e.yml
.github/workflows/test.yml

See https://github.com/Tinkoff/maskito/pull/123

ci: replace `branches-ignore` with `if`-condition to skip workflows

---

CHANGELOG.md

chore: `CHANGELOG.md` update notes for `0.1.0`-release

---

projects/core/package.json
projects/kit/package.json

Closes #130
Read about it: https://github.com/typeorm/typeorm/pull/8688/files#r812018565

fix(core): `Module parse failed: 'import' and 'export' may appear only with 'sourceType: module'`

---

CHANGELOG.md
package-lock.json
package.json
projects/demo/project.json
projects/demo/src/app/app.browser.module.ts
projects/demo/src/app/app.routes.ts
projects/demo/src/app/demo-path.ts
projects/demo/src/pages/documentation/changelog/changelog.component.ts
projects/demo/src/pages/documentation/changelog/changelog.module.ts
projects/demo/src/pages/documentation/changelog/changelog.style.less
projects/demo/src/pages/documentation/changelog/changelog.template.html
projects/demo/src/pages/pages.ts
projects/demo/src/styles.css
projects/demo/src/styles.less

chore(demo): new `Changelog` page

---

projects/angular/README.md
projects/core/README.md
projects/demo/src/app/app.routes.ts
projects/demo/src/app/demo-path.ts
projects/demo/src/pages/documentation/angular/angular.component.ts
projects/demo/src/pages/documentation/angular/angular.module.ts
projects/demo/src/pages/documentation/angular/angular.template.html
projects/demo/src/pages/documentation/angular/examples/basic-directive-approach.md
projects/demo/src/pages/documentation/angular/examples/custom-input-di-approach-inside.md
projects/demo/src/pages/documentation/angular/examples/custom-input-example.md
projects/demo/src/pages/documentation/angular/examples/di-approach-usage.md
projects/demo/src/pages/documentation/angular/examples/import-maskito-module.md
projects/demo/src/pages/documentation/maskito-libraries/maskito-libraries.component.ts
projects/demo/src/pages/documentation/maskito-libraries/maskito-libraries.template.html
projects/demo/src/pages/pages.ts
projects/kit/README.md

Closes #128
New documentation page:
https://tinkoff.github.io/maskito/angular

chore(demo): new `Angular` documentation page

---

scripts/helpers/get-all-versions.ts

See https://github.com/Tinkoff/taiga-ui/pull/3736
No error for the first release of package.

ci: fix 404 error of `getAllVersions` script

---

projects/demo-integrations/cypress/tests/recipes/phone/phone.cy.ts
projects/demo/src/pages/recipes/card/card-doc.component.ts
projects/demo/src/pages/recipes/card/card-doc.module.ts
projects/demo/src/pages/recipes/card/card-doc.template.html
projects/demo/src/pages/recipes/card/examples/1-basic/component.ts
projects/demo/src/pages/recipes/card/examples/1-basic/style.less
projects/demo/src/pages/recipes/card/examples/1-basic/template.html
projects/demo/src/pages/recipes/phone/examples/1-us-phone/component.ts
projects/demo/src/pages/recipes/phone/examples/2-ru-phone/template.html
projects/demo/src/pages/recipes/phone/phone-doc.component.ts
projects/demo/src/pages/recipes/phone/phone-doc.module.ts
projects/demo/src/pages/recipes/phone/phone-doc.template.html

chore(demo): improve `Phone` and `Card` recipes pages

---

README.md
projects/angular/README.md
projects/core/README.md
projects/kit/README.md

chore: add new Maskito logo to all `README.md`

---

projects/demo-integrations/cypress/tests/kit/date/date-min-max.cy.ts
projects/demo/src/pages/kit/date/date-mask-doc.component.ts
projects/demo/src/pages/kit/date/date-mask-doc.module.ts
projects/demo/src/pages/kit/date/date-mask-doc.template.html
projects/demo/src/pages/kit/date/examples/1-localization/component.ts
projects/demo/src/pages/kit/date/examples/1-localization/mask.ts
projects/demo/src/pages/kit/date/examples/2-min-max/component.ts
projects/demo/src/pages/kit/date/examples/2-min-max/mask.ts
projects/kit/src/lib/utils/date/segments-to-date.ts

fix(kit): `DateMask` fix wrong year that appears using the min property 

---

projects/angular/package.json

The following command also updates `@maskito/core` and `@maskito/kit` packages.
```
ng update @maskito/angular
```

feat(angular): add other maskito packages to `ng-update.packageGroup` of `package.json`

---

package.json
projects/angular/package.json
projects/kit/package.json
scripts/helpers/bump-maskito-deps.ts
scripts/helpers/bump-maskito-version-in-package-json.ts
scripts/helpers/is-maskito-package-name.ts
scripts/helpers/sync-versions.ts
scripts/helpers/update-package-json-structure.ts
scripts/postbump.ts
tsconfig.base.json

ci: postbump all maskito peer-deps on release

---

projects/demo/src/pages/kit/number/examples/4-dynamic-decimal-zero-padding/component.ts

chore(demo): `Number` improve example `Dynamic decimal zero padding`

---

projects/demo/src/pages/kit/number/examples/1-high-precision/component.ts
projects/demo/src/pages/kit/number/examples/2-separators/component.ts
projects/demo/src/pages/kit/number/examples/3-decimal-zero-padding/component.ts
projects/demo/src/pages/kit/number/examples/4-dynamic-decimal-zero-padding/component.ts

chore(demo): `Number` pads integer part with zero if empty on blur

---

projects/core/src/index.ts
projects/core/src/lib/mask.ts
projects/core/src/lib/utils/index.ts
projects/core/src/lib/utils/test/transform.spec.ts
projects/core/src/lib/utils/transform.ts
projects/demo/src/app/app.routes.ts
projects/demo/src/app/demo-path.ts
projects/demo/src/pages/documentation/core-concepts-overview/core-concepts-overview.styles.less
projects/demo/src/pages/documentation/core-concepts-overview/core-concepts-overview.template.html
projects/demo/src/pages/documentation/transformer/examples/utility-in-action-demo.md
projects/demo/src/pages/documentation/transformer/transformer.component.ts
projects/demo/src/pages/documentation/transformer/transformer.module.ts
projects/demo/src/pages/documentation/transformer/transformer.template.html
projects/demo/src/pages/pages.ts

feat(core): new utility `maskitoTransform(value, maskitoOptions)`

---

projects/demo/src/pages/kit/number/examples/maskito-parse-number-demo.md
projects/demo/src/pages/kit/number/number-mask-doc.component.ts
projects/demo/src/pages/kit/number/number-mask-doc.module.ts
projects/demo/src/pages/kit/number/number-mask-doc.template.html
projects/kit/src/index.ts
projects/kit/src/lib/masks/number/index.ts
projects/kit/src/lib/masks/number/number-mask.ts
projects/kit/src/lib/masks/number/processors/max-validation-postprocessor.ts
projects/kit/src/lib/masks/number/utils/index.ts
projects/kit/src/lib/masks/number/utils/parse-number.ts
projects/kit/src/lib/masks/number/utils/tests/parse-number.spec.ts

feat(kit): new utility `maskitoParseNumber`

---

projects/core/src/lib/classes/mask-model/utils/calibrate-value-by-mask.ts
projects/core/src/lib/classes/mask-model/utils/get-leading-fixed-characters.ts
projects/core/src/lib/classes/mask-model/utils/guess-valid-value-by-pattern.ts
projects/core/src/lib/classes/mask-model/utils/validate-value-with-mask.ts
projects/core/src/lib/utils/test/transform.spec.ts
projects/demo-integrations/cypress/tests/recipes/postfix/percentage.cy.ts
projects/demo-integrations/cypress/tests/recipes/postfix/time.cy.ts
projects/demo/src/app/app.routes.ts
projects/demo/src/app/demo-path.ts
projects/demo/src/pages/pages.ts
projects/demo/src/pages/recipes/postfix/examples/1-percentage/component.ts
projects/demo/src/pages/recipes/postfix/examples/1-percentage/mask.ts
projects/demo/src/pages/recipes/postfix/examples/2-time-pm/component.ts
projects/demo/src/pages/recipes/postfix/examples/2-time-pm/mask.ts
projects/demo/src/pages/recipes/postfix/postfix-doc.component.ts
projects/demo/src/pages/recipes/postfix/postfix-doc.module.ts
projects/demo/src/pages/recipes/postfix/postfix-doc.template.html

fix(core): show trailing fixed characters + duplicated fixed character on `Drop`

---

projects/demo/src/pages/documentation/processors/examples/preprocessor-in-action-demo.md

chore(demo): `Processors` page documentation mistake

---

projects/kit/src/lib/masks/number/number-mask.ts
projects/kit/src/lib/masks/number/processors/index.ts
projects/kit/src/lib/masks/number/processors/zero-precision-preprocessor.ts
projects/kit/src/lib/masks/number/tests/number-mask.spec.ts

fix(kit): `Number` should drop decimal part on paste from clipboard if `precision=0`

---

projects/demo-integrations/cypress/tests/kit/number/number-zero-integer-part.cy.ts
projects/demo-integrations/cypress/tests/recipes/card/card.cy.ts
projects/demo/src/pages/recipes/card/examples/1-basic/component.ts
projects/kit/src/lib/masks/number/processors/leading-zeroes-validation-postprocessor.ts
projects/kit/src/lib/masks/number/processors/not-empty-integer-part-preprocessor.ts
projects/kit/src/lib/masks/number/processors/tests/leading-zeroes-validation-postprocessor.spec.ts

fix(kit): `Number` should drop leading zeroes for negative numbers

---

projects/demo/src/pages/recipes/card/card-doc.module.ts
projects/demo/src/pages/recipes/card/examples/1-basic/component.ts
projects/demo/src/pages/recipes/card/examples/1-basic/template.html

chore(demo): `Card` enable browser autofill for documentation example

---

projects/core/src/lib/mask.ts
projects/core/src/lib/types/typed-input-event.ts
projects/core/src/lib/utils/get-line-selection.ts
projects/core/src/lib/utils/index.ts
projects/demo-integrations/cypress/tests/kit/date-range/date-range-basic.cy.ts
projects/demo-integrations/cypress/tests/kit/date/date-basic.cy.ts
projects/demo-integrations/cypress/tests/recipes/textarea/textarea-latin-letters-digits.cy.ts

feat(core): add `deleteSoftLineBackward` & `deleteSoftLineForward` support

---

projects/core/src/lib/classes/mask-model/mask-model.ts
projects/core/src/lib/classes/mask-model/tests/mask-model-fixed-characters.spec.ts
projects/demo-integrations/cypress/tests/kit/number/number-decimal-zero-padding.cy.ts

fix(core): `Maskito` losses valid characters on invalid insertion (`overwriteMode: replace`)

---

projects/demo-integrations/cypress/support/constants/index.ts
projects/demo-integrations/cypress/support/constants/real-events-support.ts
projects/demo-integrations/cypress/tests/kit/date-range/date-range-basic.cy.ts
projects/demo-integrations/cypress/tests/kit/date-time/date-time-basic.cy.ts
projects/demo-integrations/cypress/tests/kit/date/date-basic.cy.ts
projects/demo-integrations/cypress/tests/kit/time/time-basic.cy.ts
projects/demo-integrations/cypress/tests/kit/time/time-mode.cy.ts
projects/demo-integrations/cypress/tests/recipes/phone/phone.cy.ts

ci: skip tests with `cy.realPress([...])` for Firefox

---

projects/demo/src/pages/stackblitz/files/styles.css

chore(demo): `stackblitz` make better basic customization

---

nx.json

chore: add `publishable: true` to default library generator options in `nx.json`

---

projects/angular/package.json

fix(angular): `npm i @maskito/angular` throws `ERESOLVE unable to resolve dependency tree`

---

projects/core/src/lib/classes/mask-history.ts
projects/core/src/lib/mask.ts

fix(core): incorrect order of actions during update of native element

---

projects/demo-integrations/cypress/tests/kit/date-range/date-range-basic.cy.ts
projects/demo-integrations/cypress/tests/kit/date-range/date-range-min-max.cy.ts
projects/kit/src/lib/masks/date-range/date-range-mask.ts
projects/kit/src/lib/masks/date-range/processors/min-max-range-length-postprocessor.ts
projects/kit/src/lib/masks/date-range/processors/swap-dates-postprocessor.ts

Closes #203
**Paste:**
**Drop:**

feat(kit): `DateRange` swaps dates if the 2nd date is less than the 1st one

---

projects/demo-integrations/cypress/tests/angular/predicate.cy.ts
projects/demo-integrations/cypress/tests/recipes/card/card.cy.ts
projects/demo-integrations/cypress/tests/recipes/phone/phone.cy.ts
projects/demo-integrations/cypress/tests/recipes/postfix/percentage.cy.ts
projects/demo-integrations/cypress/tests/recipes/postfix/time.cy.ts
projects/demo-integrations/cypress/tests/recipes/textarea/textarea-latin-letters-digits.cy.ts
projects/demo-integrations/cypress/tests/ssr/ssr.cy.ts

chore(demo-integrations): small code refactor

---

.github/ISSUE_TEMPLATE/1-bug-report.yml

chore: improve Github issue template for new bugs

---

projects/demo/src/pages/stackblitz/components/stackblitz-starter/stackblitz-starter.component.ts

chore(demo): prerender of documentation throws `ReferenceError: document is not defined`

---

.github/workflows/build.yml
.github/workflows/deploy-preview.yml
.github/workflows/deploy.yml
.github/workflows/lint.yml
.github/workflows/test.yml

Open https://github.com/Tinkoff/maskito/actions/runs/4573547797

ci: update GitHub actions to use `Node.js 16`

---

.github/workflows/build.yml
projects/demo/project.json

Open https://github.com/Tinkoff/maskito/actions/runs/4574575570/jobs/8076355767
>  NX   ERROR  Cannot find configuration 'github' for project 'demo:generate-routes-file'
I don't know why but `"params": "ignore"` does not properly work :(
https://github.com/Tinkoff/maskito/blob/4c1033fc7d308ff7c50083f6b39c62f40663a2df/projects/demo/project.json#L220-L226

ci: fix deploy `ERROR  Cannot find configuration 'github' for project 'demo:generate-routes-file'`

---

projects/demo-integrations/cypress/tests/recipes/prefix/dynamic-pattern-mask-expression.cy.ts
projects/demo-integrations/cypress/tests/recipes/prefix/postprocessor.cy.ts
projects/demo/src/app/app.routes.ts
projects/demo/src/app/demo-path.ts
projects/demo/src/pages/pages.ts
projects/demo/src/pages/recipes/phone/examples/2-kz-phone/mask.ts
projects/demo/src/pages/recipes/phone/phone-doc.component.ts
projects/demo/src/pages/recipes/phone/phone-doc.template.html
projects/demo/src/pages/recipes/prefix/examples/1-pattern-mask/component.ts
projects/demo/src/pages/recipes/prefix/examples/1-pattern-mask/mask.ts
projects/demo/src/pages/recipes/prefix/examples/2-postprocessor/component.ts
projects/demo/src/pages/recipes/prefix/examples/2-postprocessor/mask.ts
projects/demo/src/pages/recipes/prefix/prefix-doc.component.ts
projects/demo/src/pages/recipes/prefix/prefix-doc.module.ts
projects/demo/src/pages/recipes/prefix/prefix-doc.template.html
projects/kit/src/index.ts
projects/kit/src/lib/processors/index.ts
projects/kit/src/lib/processors/prefix-postprocessor.ts

feat(kit): new `maskitoPrefixPostprocessorGenerator`

---

projects/angular/README.md
projects/demo/src/pages/documentation/overwrite-mode/examples/replace/component.ts
projects/demo/src/pages/documentation/overwrite-mode/examples/shift/component.ts
projects/demo/src/pages/documentation/processors/processors.template.html
projects/demo/src/pages/kit/date/date-mask-doc.template.html
projects/demo/src/pages/kit/time/examples/1-modes/component.ts
projects/demo/src/pages/kit/time/time-mask-doc.template.html
projects/demo/src/pages/recipes/phone/examples/1-us-phone/component.ts
projects/demo/src/pages/recipes/postfix/examples/1-percentage/component.ts
projects/demo/src/pages/recipes/postfix/examples/2-time-pm/component.ts
projects/demo/src/pages/recipes/textarea/examples/1-latin/component.ts
scripts/generate-demo-routes-file.ts

chore: small cosmetic changes

---

projects/demo-integrations/cypress/tests/kit/date/date-mode.cy.ts
projects/kit/src/lib/utils/date/parse-date-string.ts

fix(kit): fix first zero in short-format date-mask

---

.browserslistrc

chore: update `.browserslistrc`

---

projects/kit/src/lib/masks/date-time/preprocessors/valid-date-time-preprocessor.ts
projects/kit/src/lib/masks/number/processors/not-empty-integer-part-preprocessor.ts
projects/kit/src/lib/masks/number/processors/thousand-separator-postprocessor.ts
projects/kit/src/lib/masks/number/processors/zero-precision-preprocessor.ts
projects/kit/src/lib/masks/number/utils/generate-mask-expression.ts
projects/kit/src/lib/masks/number/utils/parse-number.ts
projects/kit/src/lib/processors/valid-date-preprocessor.ts
projects/kit/src/lib/utils/escape-reg-exp.ts
projects/kit/src/lib/utils/index.ts
projects/kit/src/lib/utils/tests/escape-reg-exp.spec.ts

refactor(kit): new utility `escapeRegExp`

---

projects/demo-integrations/cypress/tests/kit/number/number-prefix-postfix.cy.ts
projects/demo-integrations/cypress/tests/kit/number/number-thousand-separator.cy.ts
projects/demo-integrations/cypress/tests/kit/number/number-zero-integer-part.cy.ts
projects/kit/src/lib/masks/number/processors/thousand-separator-postprocessor.ts

fix(kit): `Number` should trim redundant thousand separators

---

CONTRIBUTING.md
package.json

chore: update `CONTRIBUTING.md`

---

projects/demo/src/pages/recipes/phone/examples/2-kz-phone/mask.ts

Open https://tinkoff.github.io/maskito/recipes/phone#kz
https://user-images.githubusercontent.com/35179038/235183079-5455bd81-b6b6-4a5e-8e4e-630441a6b22e.mov

chore(demo): improve example for `Phone` recipe

---

.github/ISSUE_TEMPLATE/1-bug-report.yml
.github/ISSUE_TEMPLATE/2-feature-request.yml
README.md
projects/demo/src/pages/documentation/maskito-libraries/maskito-libraries.component.ts
projects/demo/src/pages/documentation/maskito-libraries/maskito-libraries.template.html
projects/demo/src/pages/documentation/what-is-maskito/what-is-maskito.component.ts
projects/demo/src/pages/documentation/what-is-maskito/what-is-maskito.template.html
projects/react/README.md

chore(demo): update `Maskito libraries` documentation page

---

projects/demo/src/app/app.providers.ts
projects/demo/src/pages/documentation/js-frameworks-angular/angular-doc.template.html
projects/demo/src/pages/documentation/js-frameworks-react/react-doc.template.html

chore(demo): add `Source code` button for `Angular` & `React` pages

---

projects/react/project.json

ci(react): make `@maskito/react` publishable

---

projects/core/project.json
projects/kit/project.json

ci: use built-in `assets` property to build `core` & `kit` packages

---

projects/core/src/lib/mask.ts

fix(core): `insertFromDrop` action behaves now in the same way as `insertFromPaste`

---

README.md

Added a notice about maintainence by enterrprise to README file

chore(readme): add Taiga UI family notice

---

projects/core/src/lib/mask.ts

chore(demo): reorganize methods order of main `Maskito` class

---

.github/workflows/e2e.yml
projects/demo-integrations/cypress/support/assertions/have-ng-control-value.ts
projects/demo-integrations/cypress/support/assertions/index.ts
projects/demo-integrations/cypress/support/e2e.ts
projects/demo-integrations/cypress/tests/angular/form-control-changes.cy.ts
projects/demo-integrations/tsconfig.json
projects/demo/project.json

```ts
cy.get('tui-input').should('have.ngControlValue', '123')
```

chore(demo-integrations): new custom Cypress assertion to check Angular form control value

---

projects/core/src/index.ts
projects/core/src/lib/types/index.ts
projects/core/src/lib/types/mask-options.ts
projects/core/src/lib/types/mask-processors.ts
projects/core/src/lib/types/mask.ts
projects/core/src/lib/types/plugin.ts
projects/core/src/lib/utils/pipe.ts
projects/core/src/lib/utils/test/pipe.spec.ts
projects/demo/src/pages/recipes/phone/examples/2-kz-phone/mask.ts
projects/kit/src/lib/masks/date-range/processors/min-max-range-length-postprocessor.ts
projects/kit/src/lib/masks/date-range/processors/swap-dates-postprocessor.ts
projects/kit/src/lib/masks/date-time/postprocessors/min-max-date-time-postprocessor.ts
projects/kit/src/lib/masks/date-time/preprocessors/valid-date-time-preprocessor.ts
projects/kit/src/lib/masks/number/processors/decimal-zero-padding-postprocessor.ts
projects/kit/src/lib/masks/number/processors/leading-zeroes-validation-postprocessor.ts
projects/kit/src/lib/masks/number/processors/max-validation-postprocessor.ts
projects/kit/src/lib/masks/number/processors/non-removable-chars-deletion-preprocessor.ts
projects/kit/src/lib/masks/number/processors/not-empty-integer-part-preprocessor.ts
projects/kit/src/lib/masks/number/processors/preudo-character-preprocessor.ts
projects/kit/src/lib/masks/number/processors/thousand-separator-postprocessor.ts
projects/kit/src/lib/masks/number/processors/zero-precision-preprocessor.ts
projects/kit/src/lib/masks/number/utils/generate-mask-expression.ts
projects/kit/src/lib/masks/time/processors/max-validation-preprocessor.ts
projects/kit/src/lib/plugins/caret-guard.ts
projects/kit/src/lib/plugins/event-handler.ts
projects/kit/src/lib/processors/min-max-date-postprocessor.ts
projects/kit/src/lib/processors/postfix-postprocessor.ts
projects/kit/src/lib/processors/prefix-postprocessor.ts
projects/kit/src/lib/processors/valid-date-preprocessor.ts
projects/kit/src/lib/processors/zero-placeholders-preprocessor.ts

feat(core): expose `MaskitoMask`, `MaskitoPreprocessor`, `MaskitoPostprocessor` and `MaskitoPlugin`

---

projects/demo-integrations/cypress/tests/kit/date-time/date-time-min-max.cy.ts
projects/kit/src/lib/masks/date-time/postprocessors/min-max-date-time-postprocessor.ts

fix(kit): `DateTime` validate min / max if date is complete

---

projects/core/src/lib/utils/dom/history-events.ts
projects/core/src/lib/utils/dom/hotkey.ts

feat(core): better layout-independent way to detect Undo and Redo

---

CONTRIBUTING.md

See https://youtrack.jetbrains.com/issue/WEB-61340/WebStorm-Bundled-Vue-plugin-overrides-bundled-Angular-plugin-for-Angular-components

chore: add workaround step for WebStorm issue to `CONTRIBUTING.md`

---

README.md
projects/demo/src/pages/documentation/maskito-libraries/maskito-libraries.component.ts
projects/demo/src/pages/documentation/maskito-libraries/maskito-libraries.template.html
projects/demo/src/pages/documentation/what-is-maskito/what-is-maskito.component.ts
projects/demo/src/pages/documentation/what-is-maskito/what-is-maskito.template.html

chore(demo): update documentation about `@maskito/vue`

---

projects/demo-integrations/cypress/tests/kit/number/number-zero-integer-part.cy.ts
projects/demo/src/pages/kit/number/examples/1-high-precision/component.ts
projects/demo/src/pages/kit/number/examples/2-separators/component.ts
projects/demo/src/pages/kit/number/examples/4-decimal-zero-padding/component.ts
projects/demo/src/pages/kit/number/examples/5-dynamic-decimal-zero-padding/component.ts
projects/kit/src/lib/masks/number/number-mask.ts
projects/kit/src/lib/masks/number/plugins/index.ts
projects/kit/src/lib/masks/number/plugins/not-empty-integer.plugin.ts

feat(kit): `Number` pads empty integer part with zero on blur (if decimal part exists)

---

projects/vue/src/lib/maskito.spec.ts
projects/vue/src/lib/maskito.ts

feat(vue): support async predicate

---

CHANGELOG.md
projects/demo/src/app/modules/logo/logo.template.html

chore(demo): `CHANGELOG.md` updates

---

projects/demo-integrations/cypress/tests/kit/date/date-basic.cy.ts
projects/kit/src/lib/utils/date/validate-date-string.ts

fix(kit): `Date` allows to replace the whole selection range with zero

---

projects/kit/src/lib/plugins/event-handler.ts

Signature of `maskitoEventHandler` is similar to native [addEventListener](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener).

feat(kit): `maskitoEventHandler` accepts `AddEventListenerOptions` as the 3d optional argument

---

projects/kit/src/lib/masks/number/plugins/min-max.plugin.ts
projects/kit/src/lib/masks/number/plugins/not-empty-integer.plugin.ts
projects/kit/src/lib/processors/with-placeholder.ts

feat(kit): use capturing phase for `focus`/`blur` events in plugins

---

.github/workflows/e2e.yml
projects/core/src/lib/mask.ts
projects/demo-integrations/cypress/tests/others/native-maxlength-attribute.cy.ts
projects/demo/src/app/app.routes.ts
projects/demo/src/pages/cypress/cypress.module.ts
projects/demo/src/pages/cypress/cypress.template.html
projects/demo/src/pages/cypress/examples/2-native-max-length/component.ts

fix(core): don't ignore native attribute `maxlength`

---

projects/angular/README.md

- [x ] Docs have been added / updated (for bug fixes / features)
- [ x] Documentation content changes
404
Closes # 
200
- [x ] No

chore(angular): fix broken link in `README.md`

---

projects/demo-integrations/cypress/tests/recipes/postfix/postprocessor.cy.ts
projects/demo/src/pages/recipes/postfix/examples/2-postprocessor/component.ts
projects/demo/src/pages/recipes/postfix/examples/2-postprocessor/mask.ts
projects/demo/src/pages/recipes/postfix/postfix-doc.template.html
projects/kit/src/lib/plugins/caret-guard.ts

fix(kit): `maskitoCaretGuard` incorrectly validates the left side of constraints

---

projects/demo-integrations/cypress/tests/recipes/phone/phone.cy.ts
projects/demo/src/pages/recipes/phone/examples/2-kz-phone/mask.ts
projects/kit/src/lib/plugins/caret-guard.ts

feat(kit): `maskitoCaretGuard`'s function has the 2nd argument with current selection range

---

projects/demo-integrations/cypress/tests/kit/number/number-prefix-postfix.cy.ts
projects/demo/src/pages/kit/number/examples/3-postfix/component.ts
projects/demo/src/pages/kit/number/examples/3-postfix/mask.ts
projects/demo/src/pages/kit/number/number-mask-doc.component.ts
projects/demo/src/pages/kit/number/number-mask-doc.template.html

chore(demo): improve documentation page `Number` (add `maskitoCaretGuard`)

---

projects/demo-integrations/cypress/tests/kit/number/number-decimal-zero-padding.cy.ts
projects/kit/src/lib/masks/number/number-mask.ts
projects/kit/src/lib/masks/number/processors/decimal-zero-padding-postprocessor.ts

fix(kit): `Number` with `postfix` should be compatible with `decimalZeroPadding`

---

.github/actions/auto-push/action.yml
.github/actions/variables/action.yml
.github/workflows/lint.yml
package.json

ci: auto-push prettier and lint fixes on PRs from maintainers

---

projects/demo-integrations/cypress/tests/kit/date-range/date-range-custom-range-separator.cy.ts
projects/demo/src/pages/kit/date-range/date-range-mask-doc.component.ts
projects/demo/src/pages/kit/date-range/date-range-mask-doc.module.ts
projects/demo/src/pages/kit/date-range/date-range-mask-doc.template.html
projects/demo/src/pages/kit/date-range/examples/4-range-separator/component.ts
projects/demo/src/pages/kit/date-range/examples/4-range-separator/mask.ts
projects/kit/src/lib/masks/date-range/date-range-mask.ts

Closes #375
Added new `rangeSeparator` prop to DateRange mask

feat(kit): `DateRange` add configurable parameter `rangeSeparator`

---

projects/demo-integrations/cypress/tests/kit/date/date-min-max.cy.ts
projects/demo-integrations/cypress/tests/kit/date/date-mode.cy.ts
projects/demo/src/pages/kit/date-range/date-range-mask-doc.component.ts
projects/demo/src/pages/kit/date/date-mask-doc.component.ts
projects/kit/src/lib/types/date-mode.ts

feat(kit): `Date` & `DateRange` support new modes `yyyy`, `mm/yyyy`, `yyyy/mm`

---

projects/demo-integrations/cypress/tests/kit/time/time-mode.cy.ts
projects/demo/src/pages/kit/time/time-mask-doc.component.ts
projects/kit/src/lib/types/time-mode.ts

feat(kit): `TimeMask` support new mode `HH`

---

.github/workflows/deploy.yml
package.json
projects/demo/project.json

ci(demo): change build configuration for new custom domain

---

.github/ISSUE_TEMPLATE/1-bug-report.yml
CHANGELOG.md
README.md
package.json
projects/angular/README.md
projects/angular/package.json
projects/core/README.md
projects/core/package.json
projects/demo/src/pages/stackblitz/components/stackblitz-starter/stackblitz-starter.component.ts
projects/kit/README.md
projects/kit/package.json
projects/react/README.md
projects/react/package.json
projects/vue/README.md
projects/vue/package.json

https://tinkoff.github.io/maskito
https://maskito.dev

feat(demo): documentation is now available at https://maskito.dev

---

.github/workflows/create-release.yml
.github/workflows/deploy-preview.yml
.github/workflows/lint.yml

ci: use `TAIGA_FAMILY_BOT_PAT` secret

---

CHANGELOG.md
README.md
package.json
projects/angular/README.md
projects/angular/package.json
projects/core/README.md
projects/core/package.json
projects/core/src/lib/utils/dom/hotkey.ts
projects/demo/src/app/app.component.html
projects/demo/src/app/app.providers.ts
projects/demo/src/pages/documentation/core-concepts-overview/core-concepts-overview.template.html
projects/demo/src/pages/documentation/mask-expression/mask-expression.template.html
projects/demo/src/pages/documentation/processors/processors.template.html
projects/kit/README.md
projects/kit/package.json
projects/react/README.md
projects/react/package.json
projects/vue/README.md
projects/vue/package.json

chore: fix links after repository migration

---

.github/workflows/auto-add-to-project.yml
.github/workflows/auto-approve.yml
.github/workflows/auto-author-assign.yml
.github/workflows/auto-cleanup-caches.yml
.github/workflows/auto-dependency-review.yml
.github/workflows/auto-label.yml
.github/workflows/auto-remove-label.yml

ci: add useful workflows

---

projects/core/src/lib/mask.ts
projects/core/src/lib/utils/dom/event-listener.ts

Closes #85
Closes #418
https://github.com/taiga-family/maskito/assets/35179038/3155113a-3170-4e16-b4e3-39b465c6cdf2

feat(core): add IME composition support

---

projects/vue/src/lib/maskito.ts

fix(vue): `elementPredicate` should accept `MaskitoElementPredicateAsync` type

---

.cspell.json

See:
* https://github.com/taiga-family/linters/pull/26

chore: update `.cspell.json`

---

.github/workflows/build.yml
.github/workflows/create-release.yml
.github/workflows/deploy-preview.yml
.github/workflows/deploy.yml
.github/workflows/e2e.yml
.github/workflows/lint.yml
.github/workflows/npm-publish.yml
.github/workflows/test.yml

See https://github.com/taiga-family/maskito/actions/runs/6195312936/job/16819849637
```
Error: Unable to resolve action `codecov/codecov-action@v4`, unable to find version `v4`
```

ci: pin github action versions

---

CHANGELOG.md

chore: update `CHANGELOG.md`

---

package-lock.json
projects/react/package.json

This reverts commit 7162b38c9503e7e0535084d1baf87931aa9df219.

Revert "chore(deps): update dependency @testing-library/user-event to v14.5.1 (#507)"

---

package.json

ci: run pre-commit hooks for `yml` and `svg` files

---

package-lock.json
package.json

New Chrome 117 is incompatible with Cypress 10.
Closes #530
Cypress 10 => Cypress 12 update

chore(deps): update `Cypress@10` => `Cypress@12`

---

package-lock.json
projects/react/package.json

chore: revert

---

.github/workflows/auto-approve.yml
.github/workflows/auto-author-assign.yml
.github/workflows/auto-cleanup-caches.yml
.github/workflows/auto-dependency-review.yml
.github/workflows/auto-label.yml
.github/workflows/auto-remove-label.yml
.github/workflows/build.yml
.github/workflows/create-release.yml
.github/workflows/deploy-preview.yml
.github/workflows/deploy.yml
.github/workflows/e2e.yml
.github/workflows/lint.yml
.github/workflows/npm-publish.yml
.github/workflows/test.yml

ci: update workflows

---

.github/workflows/npm-publish.yml

ci: use name for telegram message

---

projects/demo/webpack.config.ts
tsconfig.json

chore(demo): drop legacy webpack hack

---

package-lock.json
package.json

Open https://maskito.dev/frameworks/react
___
___

chore(demo): fix React documentation examples

---

.github/workflows/auto-label.yml

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-when-a-pull-request-is-approved

ci: add `types: [submitted]` to `auto-label.yml`

---

projects/demo/src/pages/documentation/changelog/changelog.style.less
projects/demo/src/styles.less

Relates:
* https://github.com/taiga-family/taiga-ui/pull/6221

chore(demo): use `@taiga-ui/addon-doc/styles/markdown`

---

projects/demo/src/styles.less

chore(demo): fix examples in dark mode

---

package-lock.json

Relates:
* https://github.com/taiga-family/maskito/pull/783#issuecomment-1858936567

ci: fix `package-lock.json`

---

.github/renovate.json

**See:**
* https://docs.renovatebot.com/configuration-options/#npmrc
* https://github.com/taiga-family/maskito/pull/799

ci: add custom `npmrc` property to `renovate.json`

---

.github/renovate.json
package-lock.json

* https://docs.renovatebot.com/configuration-options/#postupgradetasks

ci: workaround for renovate bot

---

.github/renovate.json

See https://github.com/taiga-family/renovate-config/actions/runs/7336517711/job/19975950881
```
"name": "ExecError",
"message": "Command failed: ------------------\n/bin/sh: 0: Illegal option --\n",
```
https://docs.renovatebot.com/configuration-options/#executionmode

ci: fix `postUpgradeTasks` in `renovate.json`

---

.github/renovate.json

* https://github.com/taiga-family/maskito/pull/823
* https://github.com/taiga-family/maskito/pull/824

ci: remove `npmrc` property from `renovate.json`

---

.github/renovate.json

See:
* https://github.com/taiga-family/maskito/pull/824

ci: add `postUpgradeTasks.fileFilters` property to `renovate.json`

---

.github/workflows/auto-approve.yml

ci: refactor skipped jobs to collapse successful job report

---

projects/demo-integrations/src/support/assertions/index.ts
projects/demo-integrations/src/support/commands/index.ts
projects/demo-integrations/src/support/component.ts
projects/demo-integrations/src/support/e2e.ts

chore(demo-integrations): custom commands and assertions refactor

---

.browserslistrc
projects/demo/src/pages/documentation/browser-support/browser-support.component.ts
projects/demo/tsconfig.app.json
tsconfig.json

Relates to https://github.com/taiga-family/maskito/issues/606
https://caniuse.com/?search=beforeinput 
https://caniuse.com/?search=globalThis

feat!: bump Firefox browser support (55+ => 87+)

---

projects/demo/src/pages/cypress/examples/5-react-async-predicate/react-app.tsx
projects/demo/src/pages/frameworks/react/examples/2-element-predicate/awesome-input.tsx
projects/demo/src/pages/frameworks/react/examples/2-element-predicate/index.tsx
projects/demo/src/pages/frameworks/react/react-doc.component.ts

chore(demo): delete `@ts-nocheck` (no more required after Vue@3.4.0 update)

---

.github/workflows/deploy.yml

ci: `on: workflow_dispatch` & `on: branches: ['release/*']` in `deploy.yml`

---

.github/workflows/deploy.yml
.gitignore

ci: `on: workflow_dispatch` in `deploy.yml`

---

projects/demo-integrations/src/support/component.ts

chore(demo-integrations): stabilize command `mount` for Cypress CT

---

projects/demo/src/pages/kit/number/examples/3-postfix/component.ts
projects/demo/src/pages/kit/number/examples/3-postfix/mask.ts
projects/demo/src/pages/kit/number/number-mask-doc.component.ts
projects/demo/src/pages/kit/number/number-mask-doc.template.html
projects/demo/src/pages/kit/time/examples/2-twelve-hour-format/component.ts
projects/demo/src/pages/kit/time/examples/2-twelve-hour-format/mask.ts
projects/demo/src/pages/recipes/phone/examples/2-kz-phone/component.ts
projects/demo/src/pages/recipes/phone/examples/2-kz-phone/mask.ts
projects/demo/src/pages/recipes/phone/examples/2-kz-phone/template.html
projects/demo/src/pages/recipes/postfix/examples/2-postprocessor/component.ts
projects/demo/src/pages/recipes/postfix/examples/2-postprocessor/mask.ts
projects/demo/src/pages/recipes/prefix/examples/2-postprocessor/component.ts
projects/demo/src/pages/recipes/prefix/examples/2-postprocessor/mask.ts

chore(demo): improve some documentation examples (make them more framework agnostic)

---

projects/kit/src/lib/utils/extract-affixes.ts

chore(kit): fix `Circular dependency` warning

---

package-lock.json
projects/angular/package.json

Revert this PR from renovate bot:
* https://github.com/taiga-family/maskito/pull/1006

chore(deps): revert renovate bot pins

---

package-lock.json
package.json

`cspell` is already peer dep of `@taiga-ui/cspell-config`:
https://github.com/taiga-family/linters/blob/1b7d15ec6b3890ec8bf48535c7d615f6917effe6/projects/cspell-config/package.json#L20-L25
**Relates:**
* https://github.com/taiga-family/maskito/pull/1076
* https://github.com/taiga-family/maskito/pull/1082

chore(deps): remove `cspell` (it is already peer dep of `@taiga-ui/cspell-config`)

---

projects/demo-integrations/src/tests/component-testing/mirrored-prefix-postfix/mirrored-prefix-postfix.cy.ts
projects/demo-integrations/src/tests/kit/number/number-prefix-postfix.cy.ts

Partially solves https://github.com/taiga-family/maskito/issues/886
Done:
Rewritten e2e mirrored-prefix-postfix tests to CT

refactor(demo-integrations): rewriting e2e tests to CT(mirrored-prefix-postfix tests)

---

projects/demo/src/app/server-error-handler.ts

Relates to:
* https://github.com/taiga-family/taiga-ui/pull/7081

ci: improve `ServerErrorHandler`

---

.cspell.json
LICENSE

Add Acpekt PLC as a new license holder

chore(global): update LICENSE holder

---

.cspell.json
projects/demo/project.json
projects/demo/src/app/app.routes.ts
projects/demo/src/app/constants/demo-path.ts
projects/demo/src/pages/documentation/core-concepts-overview/core-concepts-overview.component.ts
projects/demo/src/pages/documentation/core-concepts-overview/core-concepts-overview.template.html
projects/demo/src/pages/documentation/supported-input-types/examples/password/component.ts
projects/demo/src/pages/documentation/supported-input-types/examples/password/mask.ts
projects/demo/src/pages/documentation/supported-input-types/examples/search/component.ts
projects/demo/src/pages/documentation/supported-input-types/examples/search/mask.ts
projects/demo/src/pages/documentation/supported-input-types/examples/tel/component.ts
projects/demo/src/pages/documentation/supported-input-types/examples/tel/mask.ts
projects/demo/src/pages/documentation/supported-input-types/examples/text/component.ts
projects/demo/src/pages/documentation/supported-input-types/examples/text/mask.ts
projects/demo/src/pages/documentation/supported-input-types/examples/url/component.ts
projects/demo/src/pages/documentation/supported-input-types/examples/url/mask.ts
projects/demo/src/pages/documentation/supported-input-types/supported-input-types.component.ts
projects/demo/src/pages/documentation/supported-input-types/supported-input-types.template.html
projects/demo/src/pages/pages.ts

Closes #1190
https://maskito--pr1206-supported-input-type-065ux495.web.app/supported-input-types

chore(demo): new documentation page `Supported <input /> types`

---

projects/demo-integrations/src/tests/kit/number/number-decimal-zero-padding.cy.ts
projects/kit/src/lib/masks/number/number-mask.ts
projects/kit/src/lib/masks/number/processors/empty-postprocessor.ts
projects/kit/src/lib/masks/number/processors/index.ts
projects/kit/src/lib/masks/number/utils/index.ts
projects/kit/src/lib/masks/number/utils/tests/to-number-parts.spec.ts
projects/kit/src/lib/masks/number/utils/to-number-parts.ts

fix(kit): `Number` with `decimalZeroPadding=true` should erase everything on `.00`

---

projects/core/src/lib/constants/default-element-predicate.ts

```shell
> nx run core:build
Bundling core...
Circular dependency: projects/core/src/lib/constants/index.ts -> projects/core/src/lib/constants/default-element-predicate.ts -> projects/core/src/lib/utils/index.ts -> projects/core/src/lib/utils/initial-calibration-plugin.ts -> projects/core/src/lib/utils/transform.ts -> projects/core/src/lib/constants/index.ts
index.esm.js 29.568 KB
Circular dependency: projects/core/src/lib/constants/index.ts -> projects/core/src/lib/constants/default-element-predicate.ts -> projects/core/src/lib/utils/index.ts -> projects/core/src/lib/utils/initial-calibration-plugin.ts -> projects/core/src/lib/utils/transform.ts -> projects/core/src/lib/constants/index.ts
index.cjs.js 29.933 KB
⚡ Done in 1.64s
—————————————————————————————————————————————————————————————— …
```

refactor(core): fix `Circular dependency` warning

---

package-lock.json
projects/phone/package.json

Revert the following PR:
* https://github.com/taiga-family/maskito/pull/1153

fix(phone): revert mistakenly fixated `libphonenumber-js` peer-dependency to just `>=1.0.0`

---

package-lock.json
package.json

Relates to:
* https://github.com/tramvaijs/linters/pull/28
* https://github.com/tramvaijs/linters/pull/30

chore(deps): remove npm override of `eslint-plugin-prettier`

---

projects/demo-integrations/src/tests/kit/number/number-max-validation.cy.ts
projects/demo-integrations/src/tests/kit/number/number-min-validation.cy.ts
projects/kit/src/lib/masks/number/processors/min-max-postprocessor.ts

fix(kit): `Number` should support float `min`/`max`-parameters in range -1 < x < 1

---

projects/angular/src/lib/maskito.spec.ts
projects/core/src/lib/utils/test/pipe.spec.ts
projects/core/src/lib/utils/test/transform.spec.ts
projects/demo-integrations/src/plugins/index.js
projects/demo-integrations/src/tests/component-testing/react-async-predicate/angular-wrapper.tsx
projects/demo-integrations/src/tests/component-testing/react-async-predicate/react-app.tsx
projects/demo/src/app/app.component.spec.ts
projects/demo/src/pages/frameworks/react/examples/1-use-maskito-basic-usage/example.component.tsx
projects/demo/src/pages/frameworks/react/examples/1-use-maskito-basic-usage/use-maskito-basic-usage.tsx
projects/demo/src/pages/frameworks/react/examples/2-element-predicate/awesome-input.tsx
projects/demo/src/pages/frameworks/react/examples/2-element-predicate/example.component.tsx
projects/demo/src/pages/frameworks/react/examples/2-element-predicate/index.tsx
projects/kit/src/lib/masks/number/processors/tests/leading-zeroes-validation-postprocessor.spec.ts
projects/kit/src/lib/masks/number/tests/number-mask.spec.ts
projects/kit/src/lib/masks/number/utils/tests/parse-number.spec.ts
projects/kit/src/lib/masks/time/processors/tests/max-validation-preprocessor.spec.ts
projects/kit/src/lib/processors/tests/first-date-end-separator-preprocessor.spec.ts
projects/kit/src/lib/processors/tests/normalize-date-preprocessor.spec.ts
projects/kit/src/lib/processors/tests/postfix-postprocessor.spec.ts
projects/kit/src/lib/processors/tests/prefix-postprocessor.spec.ts
projects/kit/src/lib/processors/tests/valid-date-preprocessor.spec.ts
projects/kit/src/lib/processors/tests/with-placeholder.spec.ts
projects/kit/src/lib/utils/tests/escape-reg-exp.spec.ts
projects/kit/src/lib/utils/time/tests/parse-time-string.spec.ts
projects/react/src/lib/tests/elementPredicate.spec.tsx
projects/react/src/lib/tests/useMaskito.spec.tsx

Relates to: 
* https://github.com/taiga-family/maskito/pull/1344

chore: fix eslint errors

---

projects/demo/src/app/app.component.ts
projects/demo/src/app/app.style.less
projects/demo/src/styles.less

https://github.com/user-attachments/assets/300e9d3a-630e-40d0-b1d1-dc8fae57f3c6
https://github.com/user-attachments/assets/c545f2a1-89ca-496e-8606-faf38662f8ff
Relates to:
* https://github.com/taiga-family/taiga-ui/pull/6182

chore(demo): fix smooth scrolling for anchor links

---

projects/demo/src/app/app.config.ts
projects/demo/src/pages/phone/phone-doc.component.ts
projects/demo/src/pages/phone/phone-doc.template.html

chore(demo): use `TUI_DOC_TYPE_REFERENCE_HANDLER`

---

projects/demo/src/app/app.config.ts
projects/demo/src/pages/kit/date-range/date-range-mask-doc.component.ts
projects/demo/src/pages/kit/date-time/date-time-mask-doc.component.ts
projects/demo/src/pages/kit/date/date-mask-doc.component.ts
projects/demo/src/pages/kit/number/number-mask-doc.component.ts
projects/demo/src/pages/kit/time/examples/2-twelve-hour-format/mask.ts
projects/demo/src/pages/kit/time/time-mask-doc.component.ts
projects/demo/src/pages/phone/phone-doc.component.ts
projects/demo/src/pages/stackblitz/components/stackblitz-starter/stackblitz-starter.component.ts
projects/demo/src/pages/stackblitz/stackblitz.service.ts
projects/kit/src/lib/masks/number/number-mask.ts

https://www.typescriptlang.org/tsconfig/#noUncheckedIndexedAccess
Relates: 
* https://github.com/taiga-family/linters/commit/8b23332fab807731c4e575d3ef64dc27cd8f35ef

refactor(demo): add support for `noUncheckedIndexedAccess: true`

---

projects/core/src/lib/classes/mask-model/utils/get-leading-fixed-characters.ts
projects/core/src/lib/classes/mask-model/utils/guess-valid-value-by-pattern.ts
projects/core/src/lib/classes/mask-model/utils/remove-fixed-mask-characters.ts
projects/core/src/lib/classes/mask-model/utils/validate-value-with-mask.ts
projects/kit/src/lib/masks/date-range/processors/min-max-range-length-postprocessor.ts
projects/kit/src/lib/masks/date-range/processors/swap-dates-postprocessor.ts
projects/kit/src/lib/masks/date-time/utils/is-date-time-string-complete.ts
projects/kit/src/lib/masks/date/date-mask.ts
projects/kit/src/lib/masks/number/processors/leading-zeroes-validation-postprocessor.ts
projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts
projects/kit/src/lib/processors/normalize-date-preprocessor.ts
projects/kit/src/lib/utils/date/parse-date-string.ts

https://www.typescriptlang.org/tsconfig/#noUncheckedIndexedAccess
Relates: 
* https://github.com/taiga-family/linters/commit/8b23332fab807731c4e575d3ef64dc27cd8f35ef

refactor(core,kit): add support for `noUncheckedIndexedAccess: true`

---

projects/demo/src/styles.less

chore(demo): fix dark theme inputs

---

.gitignore
projects/core/src/lib/classes/mask-model/utils/guess-valid-value-by-pattern.ts
projects/demo-integrations/src/tests/kit/time/time-step.cy.ts

fix(core): `Time` with `[step]` has unexpected cursor jump to the next segment on `ArrowUp`/`ArrowDown`

---

projects/demo-integrations/src/support/commands/index.ts
projects/demo-integrations/src/support/commands/smart-tick.ts
projects/demo-integrations/src/tests/component-testing/angular-predicate/angular-predicate.cy.ts

Relates:
* https://github.com/taiga-family/maskito/pull/1608

chore(demo-integrations): new tests for possible race condition of angular `MaskitoDirective`

---

projects/demo/src/app/app.config.ts

chore(demo): add `NG_EVENT_PLUGINS` to environment providers of demo application

---

projects/demo/src/pages/frameworks/react/examples/3-merge-ref/index.tsx
projects/demo/src/pages/frameworks/react/examples/merge-ref.md
projects/demo/src/pages/frameworks/react/react-doc.component.ts
projects/demo/src/pages/frameworks/react/react-doc.style.less
projects/demo/src/pages/frameworks/react/react-doc.template.html

Relates:
* https://github.com/taiga-family/maskito/issues/1189

chore(demo): add description how to merge Maskito React ref with other 3d-party refs

---

projects/demo/src/pages/kit/date/date-mask-doc.component.ts
projects/demo/src/pages/kit/date/date-mask-doc.template.html
projects/demo/src/pages/kit/date/examples/maskito-parse-stringify-date-demo.md

Fixes https://github.com/taiga-family/maskito/issues/1893

chore(demo): update documentation about new `maskitoParseDate` & `maskitoStringifyDate` utils

---

projects/kit/src/index.ts
projects/kit/src/lib/masks/number/index.ts
projects/kit/src/lib/masks/number/number-mask.ts
projects/kit/src/lib/masks/number/number-params.ts
projects/kit/src/lib/masks/number/utils/index.ts
projects/kit/src/lib/masks/number/utils/stringify-number.ts
projects/kit/src/lib/masks/number/utils/tests/stringify-number.spec.ts

add new maskitoStringifyNumber helper
> Not required
> https://github.com/taiga-family/maskito/issues/1966

feat(kit): new `maskitoStringifyNumber` helper

---

projects/core/src/lib/mask.ts
projects/core/src/lib/plugins/double-space.plugin.ts
projects/core/src/lib/plugins/index.ts
projects/demo-integrations/src/tests/recipes/phone/phone.cy.ts
projects/demo-integrations/src/tests/recipes/textarea/textarea-latin-letters-digits.cy.ts

fix(core): double space bar removes characters

---

projects/core/src/lib/mask.ts
projects/demo-integrations/src/tests/component-testing/number/overwrite-selection-range.cy.ts

fix(core): add possibility to overwrites `selection` property in processors

---

package-lock.json
projects/demo-integrations/package.json

https://github.com/user-attachments/assets/10272a73-772d-49be-b815-4766eb7962ad
https://github.com/user-attachments/assets/f7520d8d-1945-4412-9952-19834b1a3f99
Relates:
* https://github.com/taiga-family/maskito/pull/1953

chore(demo-integrations): fix possibility to run Cypress tests via WebStorm UI

---

projects/demo/src/pages/kit/date-time/date-time-mask-doc.component.ts
projects/demo/src/pages/kit/date-time/date-time-mask-doc.template.html
projects/demo/src/pages/kit/date-time/examples/maskito-parse-stringify-date-time-demo.md

Relates:
* https://github.com/taiga-family/maskito/pull/2055

chore(demo): add documentation about new utils `maskitoParseDateTime` & `maskitoStringifyDateTime`

---

projects/core/src/lib/mask.ts
projects/demo-integrations/src/support/commands/paste.ts
projects/demo-integrations/src/tests/component-testing/native-max-length/native-maxlength-attribute.cy.ts

fix(core): incorrect handle of paste event for `<input />` with `maxlength` attribute

---

projects/demo-integrations/src/tests/component-testing/multi-character-date-segment-separator/multi-character-date-segment-separator.cy.ts
projects/demo-integrations/src/tests/kit/date-range/date-range-basic.cy.ts
projects/demo-integrations/src/tests/kit/date-range/date-range-segments-zero-padding.cy.ts
projects/demo-integrations/src/tests/kit/date-time/date-time-basic.cy.ts
projects/demo-integrations/src/tests/kit/date/date-basic.cy.ts
projects/demo-integrations/src/tests/kit/date/date-segments-zero-padding.cy.ts
projects/demo-integrations/src/tests/recipes/placeholder/date.cy.ts
projects/kit/src/lib/utils/date/get-date-segments-order.ts
projects/kit/src/lib/utils/date/parse-date-string.ts
projects/kit/src/lib/utils/date/validate-date-string.ts
projects/kit/src/lib/utils/index.ts

https://github.com/user-attachments/assets/0e8bb66c-8115-43f2-b331-d0dc48b7334d
Fixes #2005

fix(kit): update the first digit zero-padding logic for date-related mask

---

projects/core/src/lib/classes/mask-model/mask-model.ts
projects/core/src/lib/classes/mask-model/tests/mask-model-fixed-characters.spec.ts
projects/core/src/lib/mask.ts
projects/kit/src/lib/processors/tests/valid-date-preprocessor.spec.ts
projects/kit/src/lib/processors/valid-date-preprocessor.ts

Relates:
* https://github.com/taiga-family/maskito/issues/2183

fix(core): invalid behavior of dynamic mask expression with trailing fixed characters

---

projects/core/src/lib/classes/mask-model/mask-model.ts
projects/core/src/lib/classes/mask-model/tests/dynamic-mask.spec.ts
projects/core/src/lib/classes/mask-model/tests/mask-model-fixed-characters.spec.ts

fix(core): dynamic mask switching to mask without fixed character fails on new character insertion
