projects/core/src/index.ts
projects/core/src/lib/mask.ts
projects/core/src/lib/types/index.ts
projects/core/src/lib/types/mask-options.ts
projects/core/src/lib/utils/dom/event-listener.ts
projects/core/src/lib/utils/dom/get-clipboard-data-text.ts
projects/core/src/lib/utils/dom/is-event-producing-character.ts
projects/core/src/lib/utils/index.ts
projects/core/src/lib/utils/mask-validation/adjust-fixed-mask-characters.ts
projects/core/src/lib/utils/mask-validation/validate-value-with-mask.ts
projects/demo/src/app/modules/sandbox/masks.ts
projects/demo/src/app/modules/sandbox/sandbox.component.ts
projects/demo/src/app/modules/sandbox/sandbox.template.html

```ts
type MaskExpression = Array<RegExp | string> | RegExp;
export interface MaskOptions {
mask: MaskExpression | (() => MaskExpression);
// more options
}
export declare class Mask {
constructor(elementRef: HTMLInputElement | HTMLTextAreaElement, options: MaskOptions);
destroy(): void;
}
```
```ts
import {Mask} from '@maskito/core';
const inputRef: HTMLInputElement = document.querySelector('input.css-selector');
const MASK = [
'+', '7', ' ', '(', /\d/, /\d/, /\d/, ')', ' ', /\d/, /\d/, /\d/, '-', /\d/, /\d/, '-', /\d/, /\d/
]
const inputPhone = new Mask(
this.inputRef,
{ mask: MASK }
);
```
```ts
import {Mask} from '@maskito/core';
const inputRef: HTMLInputElement = document.querySelector('input.css-selector');
const inputNumber = new Mask(
this.inputRef,
{ mask: /^\d+(\.\d*)?$/ }
); …
```

feat(core): first prototype of mask

---

projects/core/src/lib/classes/mask-model/mask-model.ts
projects/core/src/lib/mask.ts
projects/core/src/lib/types/index.ts
projects/core/src/lib/types/typed-input-event.ts
projects/core/src/lib/utils/dom/event-listener.ts
projects/core/src/lib/utils/dom/is-before-input-event-supported.ts
projects/core/src/lib/utils/index.ts
projects/demo-integrations/cypress/tests/sandbox/input-phone.cy.ts

"beforeinput"-event is more appropriate event for preprocessing of the input masking (than `keydown`):
- `keydown` **is not triggered by predictive text from native mobile keyboards**.
- `keydown` is triggered by system key combinations (we don't need them, and they should be manually filtered).
- Dropping text inside input triggers `beforeinput` (but not `keydown`).
Closes #9

refactor(kit): use `beforeinput`-event (listen to `keydown` + `paste` only for legacy browsers)

---

projects/core/src/lib/mask.ts
projects/demo/src/app/app.routes.ts
projects/demo/src/pages/documentation/browser-support/browser-support.component.ts
projects/demo/src/pages/documentation/browser-support/browser-support.module.ts
projects/demo/src/pages/documentation/browser-support/browser-support.template.html
projects/demo/src/pages/pages.ts

Open any ancient browser (with [no globalThis support](https://caniuse.com/?search=globalThis)).
For example: Firefox 64.
```
ReferenceError: globalThis is not defined
```

fix(core): `globalThis` Reference error +  new `Browser support` documentation page

---

projects/kit/src/lib/masks/time/utils/pad-time-segments.ts
projects/kit/src/lib/masks/time/utils/parse-time-string.ts
projects/kit/src/lib/processors/valid-date-preprocessor.ts
projects/kit/src/lib/utils/get-object-from-entries.ts
projects/kit/src/lib/utils/index.ts
projects/kit/src/lib/utils/parse-date-string.ts
tsconfig.base.json

Developer can mistakenly use ES-features which are not supported by all required browsers.
And there will be no error!
See https://tinkoff.github.io/maskito/documentation/browser-support
User can't use not-supported features.
Typescript throws error for them:

ci: `tsconfig` option `compilerOptions.lib` use `es2017`

---

package.json
scripts/helpers/check-prettier-changes.ts
scripts/helpers/execute.ts
scripts/postchangelog.ts
tsconfig.base.json

See https://github.com/Tinkoff/maskito/pull/118

ci: run prettier after `Changelog`-generation during release

---

scripts/helpers/get-all-versions.ts

See https://github.com/Tinkoff/maskito/actions/runs/4183887175/jobs/7248819428
```
/home/runner/work/maskito/maskito/scripts/helpers/get-last-major-version.ts:2
return Math.max(...versions.map(x => parseInt(x)), currentMajor);
^
TypeError: versions.map is not a function
at Object.getLastMajorVersion (/home/runner/work/maskito/maskito/scripts/helpers/get-last-major-version.ts:2:33)
at makeTag (/home/runner/work/maskito/maskito/scripts/npm-publish.ts:37:[29](https://github.com/Tinkoff/maskito/actions/runs/4183887175/jobs/7248819428#step:5:30))
at /home/runner/work/maskito/maskito/scripts/npm-publish.ts:27:17
at Generator.next (<anonymous>)
at fulfilled …
```

ci: script `getAllVersions` should always return array

---

projects/demo/src/app/app.providers.ts

SSR error:
```
[HLJS]  ReferenceError: window is not defined
at Object.52013 (/Users/n.barsukov/WebstormProjects/maskito/dist/demo/server/2013.js:354:4)
at __webpack_require__ (/Users/n.barsukov/WebstormProjects/maskito/dist/demo/server/main.js:235341:42)
at Function.__webpack_require__.t (/Users/n.barsukov/WebstormProjects/maskito/dist/demo/server/main.js:235377:38)
at _ZoneDelegate.invoke (/Users/n.barsukov/WebstormProjects/maskito/dist/demo/server/main.js:231532:26)
at Object.onInvoke (/Users/n.barsukov/WebstormProjects/maskito/dist/demo/server/main.js:76688:33)
at _ZoneDelegate.invoke (/Users/n.barsukov/WebstormProjects/maskito/dist/demo/server/main.js:231531:52)
at Zone.run (/Users/n.barsukov/WebstormProjects/maskito/dist/demo/server/main.js …
```

chore(demo): fix SSR `[HLJS] ReferenceError: window is not defined`

---

CHANGELOG.md
README.md
projects/core/README.md
projects/core/src/lib/classes/mask-model/mask-model.ts
projects/core/src/lib/classes/mask-model/utils/remove-fixed-mask-characters.ts
projects/core/src/lib/types/element-state.ts
projects/core/src/lib/types/mask-options.ts
projects/core/src/lib/types/selection-range.ts
projects/demo/src/pages/documentation/angular/angular.template.html
projects/demo/src/pages/documentation/core-concepts-overview/core-concepts-overview.template.html
projects/demo/src/pages/documentation/mask-expression/mask-expression.template.html
projects/demo/src/pages/documentation/maskito-libraries/maskito-libraries.template.html
projects/demo/src/pages/documentation/overwrite-mode/examples/dynamic/component.ts
projects/demo/src/pages/documentation/overwrite-mode/overwrite-mode.template.html
projects/demo/src/pages/documentation/processors/examples/element-state-demo.md
projects/demo/src/pages/documentation/processors/processors.template.html
projects/demo/src/pages/documentation/what-is-maskito/what-is-maskito.template.html
projects/demo/src/pages/kit/date-range/date-range-mask-doc.template.html
projects/demo/src/pages/kit/date/date-mask-doc.template.html
projects/demo/src/pages/kit/number/examples/4-dynamic-decimal-zero-padding/component.ts
projects/demo/src/pages/kit/number/number-mask-doc.template.html
projects/demo/src/pages/kit/time/time-mask-doc.template.html
projects/demo/src/pages/recipes/card/card-doc.template.html
projects/demo/src/pages/recipes/phone/phone-doc.template.html
projects/demo/src/pages/recipes/textarea/textarea-doc.template.html
projects/kit/src/lib/processors/zero-placeholders-preprocessor.ts

chore: improve docs

---

projects/kit/src/lib/masks/number/processors/not-empty-integer-part-preprocessor.ts
projects/kit/src/lib/masks/number/processors/tests/not-empty-integer-part-preprocessor.spec.ts

fix(kit): `Number` pads empty integer part when paste from clipboard

---

projects/demo-integrations/cypress/support/e2e.ts
projects/demo-integrations/cypress/tests/kit/number/number-decimal-separator.cy.ts
projects/demo-integrations/cypress/tests/kit/number/number-thousand-separator.cy.ts
projects/demo-integrations/cypress/tests/ssr/ssr.cy.ts
projects/demo/src/pages/kit/number/number-mask-doc.component.ts
projects/kit/src/lib/masks/number/processors/thousand-separator-postprocessor.ts
projects/kit/src/lib/masks/number/utils/generate-mask-expression.ts

fix(kit): `Number` mask throws an error on empty string in `thousandSeparator`

---

projects/kit/src/lib/masks/number/utils/parse-number.ts
projects/kit/src/lib/masks/number/utils/tests/parse-number.spec.ts

fix(kit): `maskitoParseNumber` incorrectly parses negative numbers

---

.github/workflows/test.yml
projects/angular/src/index.ts
projects/angular/src/lib/maskito.cva.ts
projects/angular/src/lib/maskito.module.ts
projects/angular/src/lib/maskito.pipe.ts
projects/angular/src/lib/maskito.spec.ts
projects/demo-integrations/cypress/tests/kit/number/number-basic.cy.ts
projects/demo-integrations/cypress/tests/kit/number/number-max-validation.cy.ts
projects/demo/src/pages/documentation/angular/angular.component.ts
projects/demo/src/pages/documentation/angular/angular.module.ts
projects/demo/src/pages/documentation/angular/angular.template.html
projects/demo/src/pages/documentation/angular/examples/3-cva/component.ts
projects/demo/src/pages/documentation/angular/examples/3-cva/template.html
projects/demo/src/pages/documentation/angular/examples/4-pipe/component.ts
projects/demo/src/pages/documentation/angular/examples/4-pipe/template.html
projects/demo/src/pages/kit/number/number-mask-doc.component.ts
projects/demo/src/pages/kit/number/number-mask-doc.template.html
projects/kit/src/lib/masks/number/number-mask.ts
projects/kit/src/lib/masks/number/utils/get-default-pseudo-separators.ts

feat(angular): add CVA and pipe

---

projects/angular/project.json

`@nrwl/angular:ng-packagr-lite` executors is for **BUILDABLE** libraries and the `@nrwl/angular:package` executor is for **PUBLISHABLE** libraries.
Read more:
* https://github.com/nrwl/nx/issues/9727#issuecomment-1091926084
* https://nx.dev/packages/angular/executors/ng-packagr-lite
* https://nx.dev/packages/angular/executors/package

fix(angular): use `@nrwl/angular:package` executor instead of `@nrwl/angular:ng-packagr-lite`

---

projects/angular/src/lib/maskito.spec.ts

1. Open https://www.npmjs.com/package/@maskito/angular?activeTab=code
2. Open `package.json`
There is not `@maskito/kit` inside `peerDependencies` of `@maskito/angular` package.

fix(angular): `@maskito/angular` should not depend on `@maskito/kit`

---

projects/demo-integrations/cypress/tests/kit/number/number-zero-integer-part.cy.ts
projects/kit/src/lib/masks/number/number-mask.ts
projects/kit/src/lib/masks/number/processors/leading-zeroes-validation-postprocessor.ts
projects/kit/src/lib/masks/number/processors/tests/leading-zeroes-validation-postprocessor.spec.ts

fix(kit): `Number` fails to trim leading zeroes after deleting of leading digit

---

projects/kit/src/lib/masks/time/processors/max-validation-preprocessor.ts
projects/kit/src/lib/masks/time/processors/tests/max-validation-preprocessor.spec.ts
projects/kit/src/lib/utils/time/validate-time-string.ts

1. Open https://tinkoff.github.io/maskito/kit/time/API
2. Drop `99:99` inside text field with a pointer

fix(kit): `Time` doesn't validate time segments on `drop` event

---

projects/demo/src/pages/documentation/mask-expression/mask-expression.template.html

The PIN code [mask expression docs](https://tinkoff.github.io/maskito/core-concepts/mask-expression) experiences a formatting issue where the `\` is removed from the final examples.
e.g.: The docs show `/^d{4}$/` but the expected value is `/^\d{4}$/`. 
Updates both the `/^\d{4}$/` and `/^\d{0,4}$/` mask expression examples for the PIN code to include the backslash for the regular expression.

docs(demo): correct pin code mask expression

---

projects/react/project.json

```
➜ nx build react          
> nx run react:build 
Some of the project react's dependencies have not been built yet. Please build these libraries before:
- core
```
```
➜ nx build react
>  NX  Running target build for project react and 1 task(s) that it depends on.
———————————————————————————————————————————————
> nx run core:build 
Bundling core...
index.esm.js 21.514 KB
index.umd.js 30.322 KB
⚡ Done in 4.44s
> nx run react:build 
Bundling react...
index.esm.js 1.482 KB
No name was provided for external module '@maskito/core' in output.globals – guessing 'core'
index.umd.js 2.29 KB
⚡ Done in 3.31s
———————————————————————————————————————————————
>  NX   SUCCESS  Running target "build" succeeded
```

ci(react): make `nx build react` to depend on `nx build core`

---

.github/actions/nodejs/action.yml
.github/workflows/test.yml
package-lock.json
package.json
projects/demo/src/app/server-error-handler.ts
projects/demo/webpack.config.ts

```
nvm use 18.15
npm start
```
it throws
```
Error: error:0308010C:digital envelope routines::unsupported
at new Hash (node:internal/crypto/hash:71:19)
at Object.createHash (node:crypto:133:10)
at BulkUpdateDecorator.hashFactory 
[...]
```
Repository is compatible with Node.js 18

chore(demo): add Node.js 18 support

---

projects/core/src/lib/mask.ts
projects/core/src/lib/utils/dom/history-events.ts

A more reliable way to determine the pressed key is used (using [KeyboardEvent#code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code)).
Also added handling of `Ctrl` + `Shift` + `Z` on Windows.
Closes: #310

fix(core): a layout-independent way to detect undo and redo shortcuts

---

projects/vue/src/lib/maskito.spec.ts

1. Run `nx build vue`
2. See `dist/vue/package.json`
It contains:
```json
"peerDependencies": {
"@maskito/core": "^0.12.1",
"vue": ">=3.0.0",
"@maskito/kit": "0.12.1"
},
```
`dist/vue/package.json` contains only
```json
"peerDependencies": {
"@maskito/core": "^0.12.1",
"vue": ">=3.0.0"
},
```

ci: drop extra peer dependency from `@maskito/vue` build

---

projects/kit/src/lib/masks/number/utils/parse-number.ts
projects/kit/src/lib/masks/number/utils/tests/parse-number.spec.ts

fix(kit): `maskitoParseNumber` should return `NaN` for all strings with no digits

---

projects/demo/src/pages/kit/number/number-mask-doc.component.ts
projects/demo/src/pages/kit/number/number-mask-doc.template.html
projects/kit/src/lib/masks/number/number-mask.ts

```ts
import {maskitoNumberOptionsGenerator} from '@maskito/kit';
const options = maskitoNumberOptionsGenerator({
isNegativeAllowed: false,
});
```
```ts
import {maskitoNumberOptionsGenerator} from '@maskito/kit';
const options = maskitoNumberOptionsGenerator({
min: 0,
});
```

feat(kit)!: delete deprecated `isNegativeAllowed` parameter from `Number` mask

---

projects/demo-integrations/cypress/tests/kit/number/number-decimal-separator.cy.ts
projects/demo-integrations/cypress/tests/kit/number/number-decimal-zero-padding.cy.ts
projects/kit/src/lib/masks/number/number-mask.ts
projects/kit/src/lib/masks/number/processors/index.ts
projects/kit/src/lib/masks/number/processors/repeated-decimal-separator-preprocessor.ts

Closes #330
Behaviour is similar to native [<input type="number">](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number) (Chrome).

fix(kit): `Number` should ignore new typed decimal separator if it already exists in text field

---

projects/kit/src/lib/plugins/caret-guard.ts

https://github.com/Tinkoff/maskito/assets/35179038/2ea976d5-9a21-4270-9c3b-9e5bbd23e8b7
Closes #371
https://github.com/Tinkoff/maskito/assets/35179038/eb4cf87c-2cd8-48cc-84b7-4ebde392a60e

fix(kit): `maskitoCaretGuard` should wait for `mouseup` before execution

---

projects/demo-integrations/cypress/tests/kit/number/number-prefix-postfix.cy.ts
projects/demo-integrations/cypress/tests/kit/number/number-zero-integer-part.cy.ts
projects/kit/src/lib/masks/number/number-mask.ts
projects/kit/src/lib/masks/number/plugins/index.ts
projects/kit/src/lib/masks/number/plugins/leading-zeroes-validation.plugin.ts

fix(kit): `Number` should remove repeated leading zeroes for integer part only on `blur`-event

---

projects/demo-integrations/cypress/tests/kit/number/number-prefix-postfix.cy.ts
projects/demo/src/pages/cypress/cypress.module.ts
projects/demo/src/pages/cypress/cypress.template.html
projects/demo/src/pages/cypress/examples/4-runtime-postfix-changes/component.ts
projects/kit/src/lib/masks/number/number-mask.ts
projects/kit/src/lib/masks/number/processors/index.ts
projects/kit/src/lib/masks/number/processors/initialization-only-preprocessor.ts
projects/kit/src/lib/masks/number/tests/number-mask.spec.ts
projects/kit/src/lib/masks/number/utils/generate-mask-expression.ts

fix(kit): `Number` has problems with run-time updates of postfix

---

projects/demo-integrations/cypress/tests/kit/date-range/date-range-separator.cy.ts
projects/demo/src/pages/kit/date-range/date-range-mask-doc.component.ts
projects/demo/src/pages/kit/date-range/date-range-mask-doc.template.html
projects/demo/src/pages/kit/date-range/examples/1-date-localization/mask.ts
projects/kit/src/lib/constants/possible-dates-separator.ts
projects/kit/src/lib/masks/date-range/date-range-mask.ts
projects/kit/src/lib/masks/date-range/processors/min-max-range-length-postprocessor.ts
projects/kit/src/lib/masks/date-range/processors/swap-dates-postprocessor.ts
projects/kit/src/lib/processors/min-max-date-postprocessor.ts
projects/kit/src/lib/processors/tests/valid-date-preprocessor.spec.ts
projects/kit/src/lib/processors/valid-date-preprocessor.ts
projects/kit/src/lib/utils/date/parse-date-range-string.ts

See https://github.com/Tinkoff/maskito/pull/376#discussion_r1268108055

deprecate(kit): use `dateSeparator` instead of deprecated `separator` for `DateRange`

---

projects/kit/src/lib/plugins/caret-guard.ts

1. Use Firefox or Safari
2. Run
```ts
import {ChangeDetectionStrategy, Component} from '@angular/core';
import {maskitoCaretGuard, maskitoNumberOptionsGenerator} from '@maskito/kit';
const numberOptions = maskitoNumberOptionsGenerator({
postfix: `$`,
});
@Component({
selector: 'test-doc-example-5',
template: `
<input
value="100$"
[maskito]="numberMask"
/>
<select>
<option>1</option>
<option>2</option>
<option>3</option>
</select>
`,
changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TestDocExample5 {
readonly numberMask = {
...numberOptions,
plugins: [
...numberOptions.plugins,
maskitoCaretGuard(value => [0, value.length - 1]),
],
};
}
```
https://github.com/taiga-family/maskito/assets/35179038/eed918cf-4ff5-4c35-a801-17ad8e4b037c …

fix(kit): `maskitoCaretGuard` doesn't work after focus on `<select />`

---

.eslintrc.js

See:
* https://github.com/taiga-family/linters/pull/27

ci: drop old `perfectionist/sort-*` eslint rules

---

projects/kit/src/lib/masks/number/processors/thousand-separator-postprocessor.ts
projects/kit/src/lib/masks/number/tests/number-mask.spec.ts
projects/kit/src/lib/masks/number/utils/generate-mask-expression.ts

Relates to https://github.com/taiga-family/taiga-ui/issues/5388
```ts
const options = maskitoNumberOptionsGenerator({
postfix: ' $',
thousandSeparator: ' ', // non-breaking space!
});
const valueWithSimpleSpaces = '45 001 $';
// first one works fine
maskitoTransform(valueWithSimpleSpaces, options); // '45 001 $'
// it will return wrong value
maskitoTransform(valueWithSimpleSpaces, options); // '45 $'
```

fix(kit): `Number` should accept all types of spaces as interchangeable characters for `thousandSeparator`

---

projects/demo-integrations/cypress/tests/addons/phone/phone-basic.cy.ts
projects/demo-integrations/cypress/tests/addons/phone/phone-non-strict.cy.ts
projects/demo/src/pages/phone/examples/3-non-strict/component.ts
projects/demo/src/pages/phone/examples/3-non-strict/mask.ts
projects/demo/src/pages/phone/examples/4-lazy-metadata/component.ts
projects/demo/src/pages/phone/examples/4-lazy-metadata/simple.md
projects/demo/src/pages/phone/phone-doc.component.ts
projects/demo/src/pages/phone/phone-doc.module.ts
projects/demo/src/pages/phone/phone-doc.template.html
projects/phone/project.json
projects/phone/src/index.ts
projects/phone/src/lib/masks/index.ts
projects/phone/src/lib/masks/phone/index.ts
projects/phone/src/lib/masks/phone/phone-mask-free.ts
projects/phone/src/lib/masks/phone/phone-mask-non-strict.ts
projects/phone/src/lib/masks/phone/phone-mask-strict.ts
projects/phone/src/lib/masks/phone/phone-mask.ts
projects/phone/src/lib/masks/phone/processors/phone-length-postprocessor.ts
projects/phone/src/lib/masks/phone/processors/validate-phone-preprocessor.ts
projects/phone/src/lib/masks/phone/tests/phone-mask.spec.ts
projects/phone/src/lib/masks/phone/utils/cut-phone-by-valid-length.ts
projects/phone/src/lib/masks/phone/utils/get-country-from-number.ts
projects/phone/src/lib/masks/phone/utils/index.ts
projects/phone/src/lib/masks/phone/utils/select-template.ts

Part of https://github.com/taiga-family/maskito/issues/323

feat(phone): add non-strict phone mask

---

.github/workflows/create-release.yml

ci: update some legacy configs inside `create-release.yml`

---

.github/workflows/auto-add-to-project.yml
.github/workflows/auto-approve.yml
.github/workflows/auto-author-assign.yml
.github/workflows/auto-cleanup-caches.yml
.github/workflows/auto-dependency-review.yml
.github/workflows/auto-label.yml
.github/workflows/auto-remove-label.yml
.github/workflows/build.yml
.github/workflows/create-release.yml
.github/workflows/deploy-preview.yml
.github/workflows/deploy.yml
.github/workflows/e2e.yml
.github/workflows/lint.yml
.github/workflows/npm-publish.yml
.github/workflows/test.yml

ci: upgrade to new actions

---

.github/workflows/auto-approve.yml
.github/workflows/e2e.yml
.github/workflows/lint.yml
.github/workflows/npm-publish.yml

ci: add auto approve validation

---

projects/kit/src/lib/masks/number/processors/decimal-zero-padding-postprocessor.ts
projects/kit/src/lib/masks/number/tests/number-mask.spec.ts

```JavaScript
const options = maskitoNumberOptionsGenerator({
decimalSeparator: ',',
thousandSeparator: '.',
decimalPseudoSeparators: ['.', ','],
precision: 2,
decimalZeroPadding: true,
});
const largeValue = '1000000';
// will return a value without zero padding
maskitoTransform(largeValue, options); // '1.000.000'
```
```JavaScript
const options = maskitoNumberOptionsGenerator({
decimalSeparator: ',',
thousandSeparator: '.',
decimalPseudoSeparators: ['.', ','],
precision: 2,
decimalZeroPadding: true,
});
const largeValue = '1000000';
// will return a value with zero padding
maskitoTransform(largeValue, options); // '1.000.000,00'
```

fix(kit): `Number` has broken zero padding when `decimalSeparator` equals to non-default value

---

projects/angular/src/lib/maskito.cva.ts
projects/angular/src/lib/maskito.directive.ts
projects/angular/src/lib/maskito.pipe.ts
projects/angular/src/lib/maskito.spec.ts

feat(angular): allow nullable options

---

projects/kit/src/lib/masks/date-range/date-range-mask.ts
projects/kit/src/lib/masks/date-time/date-time-mask.ts
projects/kit/src/lib/masks/date/date-mask.ts
projects/kit/src/lib/processors/index.ts
projects/kit/src/lib/processors/normalize-date-preprocessor.ts
projects/kit/src/lib/processors/tests/normalize-date-preprocessor.spec.ts

fix(kit): `Date` accept single character date segment during paste

---

projects/demo-integrations/cypress/tests/kit/number/number-prefix-postfix.cy.ts
projects/demo/src/pages/cypress/cypress.module.ts
projects/demo/src/pages/cypress/cypress.template.html
projects/demo/src/pages/cypress/examples/6-multi-character-prefix/component.ts
projects/kit/src/lib/processors/prefix-postprocessor.ts
projects/kit/src/lib/processors/tests/prefix-postprocessor.spec.ts

```ts
const options = maskitoNumberOptionsGenerator({
prefix: 'EUR ',
});
```
1. Empty input
2. Type `U`
Textfield value is `URE                                            `.
Closes #595
Textfield value is `EUR `.

fix(kit): `PrefixPostprocessor` has problems with multi-character prefix

---

projects/demo-integrations/cypress/tests/addons/phone/phone-separator.cy.ts
projects/demo/src/pages/phone/phone-doc.component.ts
projects/demo/src/pages/phone/phone-doc.template.html
projects/phone/src/lib/masks/phone/phone-mask-non-strict.ts
projects/phone/src/lib/masks/phone/phone-mask-strict.ts
projects/phone/src/lib/masks/phone/phone-mask.ts
projects/phone/src/lib/masks/phone/utils/get-phone-template.ts

Closes #680 
added new parameter `separator` with default value `-`

feat(phone): add ability to configure the separator

---

scripts/generate-demo-routes-file.ts

Open https://maskito.dev/addons/phone/API

ci: fix prerender of page `https://maskito.dev/addons/phone/API`

---

.npmrc
package-lock.json

```
➜  nvm use 16
Now using node v16.20.0 (npm v8.19.4)
➜  npm ci
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: maskito@1.9.0
npm ERR! notsup Not compatible with your version of node/npm: maskito@1.9.0
npm ERR! notsup Required: {"node":">= 18","npm":">= 9","yarn":"Please use npm instead of yarn to install dependencies"}
npm ERR! notsup Actual:   {"npm":"8.19.4","node":"v16.20.0"}
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/n.barsukov/.npm/_logs/2023-12-11T13_41_00_619Z-debug-0.log
```

ci: use `engine-strict=true` in `.npmrc`

---

projects/angular/src/lib/maskito.directive.ts
projects/core/src/index.ts
projects/core/src/lib/constants/default-element-predicate.ts
projects/core/src/lib/types/element-predicate.ts
projects/demo/src/pages/cypress/examples/1-predicate/component.ts
projects/demo/src/pages/cypress/examples/5-react-async-predicate/react-app.tsx
projects/demo/src/pages/frameworks/angular/examples/1-nested/component.ts
projects/react/src/lib/tests/elementPredicate.spec.tsx
projects/react/src/lib/useMaskito.ts
projects/vue/src/lib/maskito.ts

**`@maskito/core` source code:**
```ts
export type MaskitoElementPredicate = (
element: HTMLElement,
) => HTMLInputElement | HTMLTextAreaElement;
export type MaskitoElementPredicateAsync = (
element: HTMLElement,
) => Promise<HTMLInputElement | HTMLTextAreaElement>;
```
___
**Your code:**
```ts
import {
MaskitoElementPredicate,
MaskitoElementPredicateAsync,
} from '@maskito/core';
const syncPredicate: MaskitoElementPredicate = element =>
element.querySelectorAll('input')[1]!;
const asyncPredicate: MaskitoElementPredicateAsync = async element =>
Promise.resolve(element.querySelectorAll('input')[1]!);
```
**`@maskito/core` source code:**
```ts
export type MaskitoElementPredicate = (
element: HTMLElement,
) =>
| HTMLInputElement
| …
```

feat(core)!: merge `MaskitoElementPredicate` & `MaskitoElementPredicateAsync` into single type

---

.github/workflows/build.yml
.github/workflows/deploy-preview.yml
.github/workflows/deploy.yml
.github/workflows/e2e.yml
.github/workflows/lint.yml
.github/workflows/npm-publish.yml
.github/workflows/test.yml

See this [job](https://github.com/taiga-family/maskito/actions/runs/7209213560/job/19639698592?pr=767):
```
>  NX   Invalid Cache Directory for Task "core:build"
The local cache artifact in "/home/runner/work/maskito/maskito/.nx/cache/16217488490994067861" was not generated on this machine.
As a result, the cache's content integrity cannot be confirmed, which may make cache restoration potentially unsafe.
If your machine ID has changed since the artifact was cached, run "nx reset" to fix this issue.
Read about the error and how to address it here: https://nx.dev/recipes/troubleshooting/unknown-local-cache
```

ci: add missed `taiga-family/ci/actions/setup/variables`

---

projects/demo/src/pages/kit/date-range/date-range-mask-doc.component.ts
projects/demo/src/pages/kit/date-range/date-range-mask-doc.template.html
projects/kit/src/lib/masks/date-range/date-range-mask.ts

```ts
import {maskitoDateRangeOptionsGenerator} from '@maskito/kit';
const options = maskitoDateRangeOptionsGenerator({
mode: 'mm/dd/yyyy',
separator: '/', // <-------- deprecated
rangeSeparator: ' ~ ',
});
```
```ts
import {maskitoDateRangeOptionsGenerator} from '@maskito/kit';
const options = maskitoDateRangeOptionsGenerator({
mode: 'mm/dd/yyyy',
dateSeparator: '/',
rangeSeparator: ' ~ ',
});
```

feat(kit)!: delete deprecated `separator` for `DateRange` (use use `dateSeparator` instead)

---

package-lock.json
projects/vue/package.json

`vue@3.3.13` is latest.
```
projects
├── demo
│   ├── package.json
│   │   ├── dependencies
│   │   │   ├── "vue": "3.3.12"
└── vue
│   ├── package.json
│   │   ├── peerDependencies
│   │   │   ├── "vue": ">3.0.0"
```
Delete `node_modules` & `package-lock.json`.
Run `npm i --workspaces --include-workspace-root`:
```
➜  npm i --workspaces --include-workspace-root
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @maskito/vue@1.9.0
npm ERR! Found: vue@3.3.12
npm ERR! node_modules/vue
npm ERR!   vue@"3.3.12" from @maskito/demo@undefined
npm ERR!   projects/demo
npm ERR!     @maskito/demo@undefined
npm ERR!     node_modules/@maskito/demo
npm ERR!       workspace projects/demo from the root project
npm …
```

ci: fix `npm i` command

---

projects/core/src/index.ts
projects/core/src/lib/utils/dom/set-element-value.ts
projects/core/src/lib/utils/dom/update-element.ts
projects/core/src/lib/utils/index.ts
projects/core/src/lib/utils/initial-calibration-plugin.ts
projects/kit/src/lib/masks/number/plugins/leading-zeroes-validation.plugin.ts
projects/kit/src/lib/masks/number/plugins/min-max.plugin.ts
projects/kit/src/lib/masks/number/plugins/not-empty-integer.plugin.ts
projects/kit/src/lib/plugins/add-on-focus.ts
projects/kit/src/lib/plugins/remove-on-blur.ts
projects/kit/src/lib/processors/with-placeholder.ts

Closes #804
Every dispatchEvent of input event now passes the bubbling stage, and it works with React

fix: add `{bubbles:true}` for `input` events inside all built-in plugins to support `ReactSyntheticEvent` 

---

projects/kit/src/lib/masks/number/utils/parse-number.ts
projects/kit/src/lib/masks/number/utils/tests/parse-number.spec.ts

```ts
maskitoParseNumber('0.42 lbs.') // NaN
maskitoParseNumber('1 000.42 lbs.') // NaN
maskitoParseNumber('lbs. 42') // 0.42
```
```ts
maskitoParseNumber('0.42 lbs.') // 0.42
maskitoParseNumber('1 000.42 lbs.') // 1 000.42
maskitoParseNumber('lbs. 42') // 42
```
**Partially** solves https://github.com/taiga-family/maskito/issues/703
Relates to https://github.com/taiga-family/maskito/pull/816

fix(kit): `maskitoParseNumber` cannot parse prefix/postfix with points

---

projects/core/src/lib/mask.ts
projects/demo-integrations/src/tests/component-testing/placeholder/placeholder-dispatch-input-events.cy.ts
projects/demo-integrations/src/tests/component-testing/utils.ts
projects/kit/src/lib/processors/tests/with-placeholder.spec.ts
projects/kit/src/lib/processors/with-placeholder.ts

fix(core): drop some excess dispatches of `Input`-event

---

projects/demo/webpack.config.ts

Open https://maskito.dev/frameworks/vue
Relates to https://github.com/vuejs/core/issues/10039

chore(demo): workaround for `vue@3.4.0` regression

---

projects/demo-integrations/src/tests/kit/number/number-prefix-postfix.cy.ts
projects/kit/src/lib/constants/unicode-characters.ts
projects/kit/src/lib/masks/number/number-mask.ts
projects/kit/src/lib/masks/number/processors/index.ts
projects/kit/src/lib/masks/number/processors/not-empty-integer-part-preprocessor.ts
projects/kit/src/lib/masks/number/processors/tests/not-empty-integer-part-preprocessor.spec.ts
projects/kit/src/lib/masks/number/tests/number-mask.spec.ts

Relates to https://github.com/taiga-family/maskito/pull/816#discussion_r1446023930
Closes https://github.com/taiga-family/maskito/issues/703

fix(kit): `Number` should use zero-width space if prefix ends with decimal separator

---

projects/demo-integrations/src/tests/recipes/placeholder/us-phone.cy.ts
projects/demo/src/pages/recipes/placeholder/examples/1-cvc-code/component.ts
projects/demo/src/pages/recipes/placeholder/examples/2-phone/component.ts
projects/demo/src/pages/recipes/placeholder/examples/2-phone/mask.ts
projects/demo/src/pages/recipes/placeholder/examples/3-date/component.ts
projects/demo/src/pages/recipes/placeholder/placeholder-doc.component.ts
projects/kit/src/lib/processors/tests/with-placeholder.spec.ts
projects/kit/src/lib/processors/with-placeholder.ts

fix(kit): `Placeholder` is not compatible with `maskitoEventHandler` + `focus`/`blur` events

---

projects/kit/src/lib/masks/number/number-mask.ts
projects/kit/src/lib/masks/number/tests/number-mask.spec.ts

1. Open https://maskito.dev/kit/number#high-precision
2. Enter full width digit (e.g. `１`)
https://github.com/taiga-family/maskito/assets/35179038/e29fe2e1-3cea-41e0-b5b5-11f6ea4758c1

fix(kit): `Number` rejects the first time input of full width digits

---

projects/react/.babelrc
projects/react/project.json

Run `nx build react`
<br />
Learn more: https://babeljs.io/docs/babel-preset-env#usebuiltins
Closes #956

fix(react): `@maskito/react` library should not include `core-js` imports

---

projects/react/project.json

`@maskito/react@1.9.0` has `umd`-format (for Node.js; for example `Jest`-tests):
___
`@maskito/react@2.0.0` does **not** have `umd`-format
___
It is `2.0.0`'s regression bug. 
It is connected to `Nx` [14.1.8](https://github.com/nrwl/nx/releases/tag/14.1.8)-release.
Default value of `format` for `rollup` is set ESM only.
Learn more: https://github.com/nrwl/nx/pull/10349
`@maskito/react` includes again both ESM and CJS (previous UMD users can use CJS).
Closes #983

fix(react): `@maskito/react` includes again missing `cjs` module format

---

projects/demo-integrations/src/tests/kit/date/date-segments-zero-padding.cy.ts
projects/kit/src/lib/constants/date-segment-max-values.ts
projects/kit/src/lib/constants/index.ts
projects/kit/src/lib/masks/date-range/date-range-mask.ts
projects/kit/src/lib/masks/date-range/tests/date-segments-zero-padding.spec.ts
projects/kit/src/lib/masks/date-time/date-time-mask.ts
projects/kit/src/lib/masks/date-time/tests/date-segments-zero-padding.spec.ts
projects/kit/src/lib/masks/date/date-mask.ts
projects/kit/src/lib/masks/date/tests/date-mask.spec.ts
projects/kit/src/lib/processors/date-segments-zero-padding-postprocessor.ts
projects/kit/src/lib/processors/index.ts
projects/kit/src/lib/utils/date/tests/parse-date-range-string.spec.ts
projects/kit/src/lib/utils/date/validate-date-string.ts

See this comment:
* https://github.com/taiga-family/maskito/pull/907#issuecomment-1911652959

feat(kit): `Date` & `DateRange` & `DateTime` has improved zero-padding support for browser autofill & IME composition

---

projects/kit/src/lib/masks/number/utils/parse-number.ts
projects/kit/src/lib/masks/number/utils/tests/parse-number.spec.ts

Relates https://github.com/taiga-family/maskito/pull/864

fix(kit): `maskitoParseNumber` should interpret japanese prolonged sound mark as pseudo minus

---

projects/angular/src/lib/maskito.directive.ts
projects/demo-integrations/src/tests/component-testing/angular/disable-mask-on-null.cy.ts
projects/demo-integrations/src/tests/component-testing/utils.ts
projects/react/src/lib/useMaskito.ts
projects/vue/src/lib/maskito.ts

fix: totally disable `Maskito` if nullable options are passed inside `@maskito/{angular,react,vue}`

---

projects/core/tsconfig.lib.json
projects/kit/tsconfig.lib.json
projects/phone/tsconfig.lib.json
projects/vue/tsconfig.lib.json

chore: fix IDE error when import `is not under rootDir`

---

projects/demo-integrations/src/tests/kit/date/date-mode.cy.ts
projects/kit/src/lib/processors/normalize-date-preprocessor.ts

Closes https://github.com/taiga-family/maskito/issues/1176
Closes https://github.com/taiga-family/maskito/issues/836
Done:
1. Fixed `Date` formatting errors with those date modes: `mm/yyyy`, `yyyy/mm`, `mm/yy`
2. Added `integration tests` for those error cases

fix(kit): `Date` formatting errors for `mm/yyyy`, `yyyy/mm`, `mm/yy` modes

---

projects/demo-integrations/src/tests/component-testing/placeholder/placeholder-has-same-characters-as-textfield.cy.ts
projects/kit/src/lib/processors/with-placeholder.ts

fix(kit): `Placeholder` can have now the same character as textfield's value

---

package.json

```shell
> git commit -m "chore: any commit message"
⚠ Some of your tasks use `git add` command.
Please remove it from the config since all modifications made by tasks will be automatically added to the git commit index.
```
No warning
Learn body of the following PR to get more details:
* https://github.com/taiga-family/taiga-ui/pull/3559

chore: remove `git add` command from `lint-staged`

---

projects/demo-integrations/src/tests/kit/number/number-minus-sign.cy.ts
projects/demo-integrations/src/tests/kit/number/number-zero-integer-part.cy.ts
projects/kit/src/lib/masks/number/processors/not-empty-integer-part-preprocessor.ts

Open https://maskito.dev/kit/number/API?decimalSeparator=.&precision=2
Empty textfield => Type `.` => `0.` ✅ 
Textfield's value is `1.23` => select all => Type `.` => empty textfield ❌ 
Textfield's value is `1.23` => select all => Type `.` => `0.` ✅ 
Closes #1219

fix(kit): `Number` pads integer part with zero if user selects all and then types decimal separator

---

projects/vue/package.json

Revert this PR:
* https://github.com/taiga-family/maskito/pull/1181

fix(vue): revert mistakenly fixated `vue` peer-dependency to just `>=3.0.0`

---

projects/react/package.json

Revert these PRs:
* https://github.com/taiga-family/maskito/pull/1155
* https://github.com/taiga-family/maskito/pull/1156

fix(react): revert mistakenly fixated `react` & `react-demo` peer-dependencies to just `>=16.8`

---

projects/demo-integrations/src/tests/kit/time/time-mode.cy.ts
projects/demo/src/pages/documentation/supported-input-types/supported-input-types.template.html
projects/demo/src/pages/kit/time/time-mask-doc.component.ts
projects/kit/src/lib/masks/date-time/date-time-mask.ts
projects/kit/src/lib/masks/date-time/postprocessors/min-max-date-time-postprocessor.ts
projects/kit/src/lib/masks/date-time/preprocessors/valid-date-time-preprocessor.ts
projects/kit/src/lib/masks/time/processors/max-validation-preprocessor.ts
projects/kit/src/lib/masks/time/processors/tests/max-validation-preprocessor.spec.ts
projects/kit/src/lib/masks/time/time-mask.ts
projects/kit/src/lib/types/time-mode.ts
projects/kit/src/lib/utils/time/parse-time-string.ts
projects/kit/src/lib/utils/time/tests/parse-time-string.spec.ts
projects/kit/src/lib/utils/time/tests/to-time-string.spec.ts
projects/kit/src/lib/utils/time/to-time-string.ts
projects/kit/src/lib/utils/time/validate-time-string.ts

Closes https://github.com/taiga-family/maskito/issues/38

feat(kit): `Time` supports `SS.MSS` & `MM.SS.MSS` modes

---

projects/demo-integrations/src/tests/recipes/placeholder/us-phone.cy.ts
projects/kit/src/lib/processors/with-placeholder.ts

fix(kit): move caret after attempt to erase fixed character in a mask with `Placeholder`

---

package-lock.json
projects/demo/package.json

```shell
Command failed: npm i --workspaces --include-workspace-root
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: @maskito/demo@undefined
npm error Found: @angular/common@15.2.10
npm error node_modules/@angular/common
npm error   @angular/common@"15.2.10" from @maskito/demo@undefined
npm error   projects/demo
npm error     @maskito/demo@undefined
npm error     node_modules/@maskito/demo
npm error       workspace projects/demo from the root project
npm error
npm error Could not resolve dependency:
npm error peer @angular/common@">=16.0.0" from @ng-web-apis/common@4.0.0
npm error node_modules/@ng-web-apis/common
npm error   peer @ng-web-apis/common@">=2.0.0" from @ng-web-apis/universal@3.0.7
npm error …
```

chore(deps): fix renovate error `Could not resolve dependency`

---

projects/core/src/lib/mask.ts

fix(core): correct handling of browser autofill/suggestion in Firefox

---

projects/demo/src/app/app.routes.ts
projects/demo/src/app/constants/demo-path.ts
projects/demo/src/pages/documentation/real-world-form/index.html
projects/demo/src/pages/documentation/real-world-form/index.less
projects/demo/src/pages/documentation/real-world-form/index.ts
projects/demo/src/pages/pages.ts

Closes #201
[See new page](https://maskito--pr1325-browser-autofill-pag-r9tjn4y0.web.app/real-world-form)
___
New documentation page is required to debug Maskito in real world conditions.
For example, this page can be used to debug browser autofill.
For instance, see reproduction of this bug:
* https://github.com/taiga-family/maskito/issues/1322
https://github.com/taiga-family/maskito/assets/35179038/f543504d-69d4-4c35-bdc8-e982ce7c70df

chore(demo): create documentation page `Maskito in Real World Form`

---

projects/core/src/index.ts
projects/core/src/lib/plugins/change-event-plugin.ts
projects/core/src/lib/plugins/index.ts
projects/core/src/lib/plugins/initial-calibration-plugin.ts
projects/core/src/lib/plugins/strict-composition-plugin.ts
projects/core/src/lib/utils/index.ts
projects/demo-integrations/src/tests/component-testing/change-event-plugin/change-event-plugin.cy.ts
projects/demo-integrations/src/tests/component-testing/utils.ts
projects/demo/src/pages/documentation/plugins/examples/4-change-event/component.ts
projects/demo/src/pages/documentation/plugins/examples/4-change-event/mask.ts
projects/demo/src/pages/documentation/plugins/plugins.component.ts
projects/demo/src/pages/documentation/plugins/plugins.template.html

feat(core): new built-in `maskitoChangeEventPlugin`

---

projects/demo/src/pages/phone/examples/5-focus-blur-events/component.ts
projects/demo/src/pages/phone/examples/5-focus-blur-events/mask.ts
projects/demo/src/pages/phone/phone-doc.component.ts
projects/demo/src/pages/phone/phone-doc.template.html
projects/phone/src/lib/masks/phone/phone-mask-strict.ts

Closes #1134
Relates to these lines from Taiga UI:
https://github.com/taiga-family/taiga-ui/blob/8da2d665467b1d61e277f5574a09646b81e7ca99/projects/kit/components/input-phone-international/input-phone-international.component.ts#L188-L199

feat(phone)!: remove built-in `RemoveOnBlur` / `AddOnFocus` plugins from `@maskito/phone`

---

projects/demo/src/pages/kit/time/time-mask-doc.component.ts
projects/kit/src/lib/masks/date-time/preprocessors/valid-date-time-preprocessor.ts
projects/kit/src/lib/masks/time/processors/max-validation-preprocessor.ts
projects/kit/src/lib/masks/time/utils/parse-time.ts
projects/kit/src/lib/masks/time/utils/stringify-time.ts
projects/kit/src/lib/masks/time/utils/tests/stringify-time.spec.ts
projects/kit/src/lib/utils/time/index.ts
projects/kit/src/lib/utils/time/pad-end-time-segments.ts
projects/kit/src/lib/utils/time/pad-start-time-segments.ts
projects/kit/src/lib/utils/time/pad-time-segments.ts

fix(kit): `maskitoStringifyTime` was adding `0` on the wrong side

---

projects/demo-integrations/src/tests/component-testing/placeholder/placeholder-partial-removal-on-blur.cy.ts
projects/kit/src/lib/processors/tests/with-placeholder.spec.ts
projects/kit/src/lib/processors/with-placeholder.ts

```ts
const PLACEHOLDER = 'xx xx xx xx##';
const { plugins, ...rest } = maskitoWithPlaceholder(PLACEHOLDER);
const mask: MaskitoOptions = {
...rest,
mask: PLACEHOLDER.split('').map((x) => (x === 'x' || x === '#' ? /\d/ : x)),
plugins: [
...plugins,
maskitoEventHandler('focus', (element) => {
const initialValue = element.value || '';
maskitoUpdateElement(
element,
initialValue + PLACEHOLDER.slice(initialValue.length)
);
}),
maskitoEventHandler('blur', (element) =>
maskitoUpdateElement(element, element.value.replace(/#/g, ''))
),
],
};
```
Enter incomplete value and blur => the textfield's value still includes `#` (despite logic inside `maskitoEventHandler('blue')`!).
Explore the following reproduction:
* https://stackblitz.com/edit/maskito-issue-1441

fix(kit): `Placeholder` should support partial programmatic removal of placeholder's characters

---

projects/demo/src/pages/stackblitz/stackblitz.service.ts

Open https://maskito.dev/stackblitz
It throws
```
403 ERROR
The request could not be satisfied.
___
Request blocked. We can't connect to the server for this app or website at this time.
There might be too much traffic or a configuration error.
Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, 
you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
```
Relates:
* https://github.com/stackblitz/sdk/issues/24

chore(demo): make StackBlitz great again

---

projects/core/src/index.ts
projects/kit/src/index.ts
projects/kit/src/lib/masks/time/index.ts

Fix the following errors:
```
Re-exporting a type when 'verbatimModuleSyntax' is enabled requires using 'export type'
```
https://www.typescriptlang.org/tsconfig/#verbatimModuleSyntax
Relates:
* https://github.com/taiga-family/linters/commit/8b23332fab807731c4e575d3ef64dc27cd8f35ef

refactor: add support for `verbatimModuleSyntax: true`

---

tsconfig.spec.json

```
projects/core/src/lib/utils/test/get-word-selection.spec.ts:1:27 - error
TS1286: ESM syntax is not allowed in a CommonJS module when 'verbatimModuleSyntax' is enabled.
import {describe, expect, it} from '@jest/globals';
```

chore: add `verbatimModuleSyntax: false` to `tsconfig.spec.json`

---

projects/core/src/lib/mask.ts
projects/core/src/lib/utils/dom/event-listener.ts
projects/demo-integrations/src/tests/kit/date-range/date-range-basic.cy.ts
projects/demo-integrations/src/tests/kit/date/date-basic.cy.ts
projects/demo-integrations/src/tests/recipes/textarea/textarea-latin-letters-digits.cy.ts

https://github.com/user-attachments/assets/0e6a603a-e2e5-4729-bab8-aae9918871b4
https://github.com/user-attachments/assets/4a0d976f-c310-49bd-977c-84f655ad833d
Closes #917

fix(core): fix scroll for masked narrow textfields

---

projects/core/src/lib/classes/mask-model/utils/apply-overwrite-mode.ts
projects/demo-integrations/src/tests/component-testing/overwrite-mode/overwrite-mode-replace.cy.ts

1. Open https://maskito.dev/core-concepts/overwrite-mode#replace
2. Replace all content with `1234`
3. Select `1|23|4`
4. Press `0`
**Expected behavior:** `104`
**Actual behavior:** `1034`

fix(core): incorrect behavior of `overwriteMode = replace` if selection contains several characters

---

package.json

This reverts commit 240223b0513d67fb5509fffb8ebff5fa84204200.

Revert "ci: add temporary fallback command for unsuccessful npm publish (#1698)"

---

projects/demo-integrations/src/support/commands/index.ts
projects/demo-integrations/src/support/commands/paste.ts
projects/demo-integrations/src/tests/kit/date-time/date-time-basic.cy.ts
projects/kit/src/lib/masks/date-time/date-time-mask.ts
projects/kit/src/lib/masks/date-time/postprocessors/min-max-date-time-postprocessor.ts
projects/kit/src/lib/masks/date-time/preprocessors/valid-date-time-preprocessor.ts
projects/kit/src/lib/masks/date-time/utils/parse-date-time-string.ts
projects/kit/src/lib/masks/date-time/utils/tests/parse-date-time-string.spec.ts

1. Open https://maskito.dev/kit/date-time/API
2. Try to paste the following value:
```
021120181620
```
**Expected**: `02.11.2018, 16:20` ✅
**Actual**: `02.11.2018, 20` ❌
Fixes #1776

fix(kit): `DateTime` fails to process value without any separators (paste from clipboard)

---

projects/demo-integrations/src/tests/component-testing/number/with-initial-value.cy.ts
projects/demo-integrations/src/tests/kit/number/number-zero-integer-part.cy.ts
projects/kit/src/lib/masks/number/processors/thousand-separator-postprocessor.ts

fix(kit): `Number` incorrectly shift caret for 1st time insertion into textfield with initial value

---

projects/demo-integrations/src/tests/kit/date-time/date-time-meridiem.cy.ts
projects/demo-integrations/src/tests/kit/time/time-meridiem.cy.ts
projects/demo-integrations/src/tests/kit/time/time-step.cy.ts
projects/kit/src/lib/masks/date-time/date-time-mask.ts
projects/kit/src/lib/masks/time/time-mask.ts

https://maskito.dev/kit/time/API?mode=HH:MM%20AA&step=1
https://github.com/user-attachments/assets/cc57859f-081c-4da3-a373-7ee019c0e8ef

fix(kit): `Time` & `DateTime` has conflicts between `step` & `AM/PM` features

---

projects/kit/src/lib/plugins/selection-change.ts

fix(kit): `SelectionChangeHandler` does not work for Safari after programmatic update of textfield value

---

projects/demo-integrations/src/tests/addons/phone/phone-strict.cy.ts
projects/phone/src/lib/masks/phone/phone-mask-non-strict.ts
projects/phone/src/lib/masks/phone/phone-mask-strict.ts
projects/phone/src/lib/masks/phone/processors/validate-phone-preprocessor.ts

fix(phone): `Phone` should accept incomplete phone number of selected country (even with `strict=true`)

---

package.json
projects/angular/package.json
projects/core/package.json
projects/kit/package.json
projects/phone/package.json
projects/react/package.json
projects/vue/package.json

I was looking for an updated library to perform input masking in react using the proposed keywords. I could only find this library after having reached “text-mask” through reddit and seeing it as an option in the list of alternatives.
It seems to me that by updating the list of keywords (I don't know if there are restrictions on the number or content) the library could have more visibility and more contributors, which it deserves since it managed to solve my problems.
> Not required
> Not required

chore: update `keywords` for publishable libraries

---

projects/demo-integrations/src/tests/kit/time/time-mode.cy.ts
projects/demo/src/pages/kit/time/time-mask-doc.component.ts
projects/kit/src/lib/masks/time/utils/tests/parse-time.spec.ts
projects/kit/src/lib/masks/time/utils/tests/stringify-time.spec.ts
projects/kit/src/lib/types/time-mode.ts
projects/kit/src/lib/utils/time/tests/parse-time-string.spec.ts
projects/kit/src/lib/utils/time/tests/to-time-string.spec.ts

Fixes https://github.com/taiga-family/maskito/issues/1996
Hi guys. I created small PR with new  `MM:SS` mode for time kit.

feat(kit): `Time` supports `MM:SS` mode

---

projects/kit/src/lib/masks/date/utils/parse-date.ts
projects/kit/src/lib/masks/date/utils/tests/parse-date.spec.ts

The function maskitoParseDate had to return a non-nullable Date type data, as opposed to its equivalent for the number type, which could return NaN.
This caused the function to prematurely return wrong dates, for example, following a mode of “dd/mm/yyyy”, when the first two digits of the year were completed the function already returned a premature result since it entered conditionals that correspond to other modes such as “mm/yy”.
With this pull request the return type of the function is modified as well as the expected result, until the function does not receive a string of characters of the same length as the mode of use, it will not try to parse the date.
> Not required
https://github.com/taiga-family/maskito/issues/2007

fix(kit): `maskitoParseDate` should return `null` for incompleted date string

---

package.json
projects/demo-integrations/src/tests/component-testing/angular-predicate/angular-predicate.cy.ts

Run 
```
npm run cy:run
```
Its logs will contain the following error:
```
ERROR in src/tests/component-testing/angular-predicate/angular-predicate.cy.ts:41:49 - error
TS7006: Parameter 'element' implicitly has an 'any' type.
41                 maskitoElementPredicate: async (element) =>
~~~~~~~
```

ci: run typecheck for integrations tests too

---

projects/kit/src/lib/constants/default-min-max-dates.ts
projects/kit/src/lib/masks/date-time/date-time-mask.ts
projects/kit/src/lib/masks/date-time/date-time-params.ts
projects/kit/src/lib/masks/date-time/utils/parse-date-time.ts
projects/kit/src/lib/masks/date-time/utils/stringify-date-time.ts
projects/kit/src/lib/masks/date-time/utils/tests/parse-date-time.spec.ts
projects/kit/src/lib/masks/date-time/utils/tests/stringify-date-time.spec.ts

add new `maskitoParseDateTime` and `maskitoStringifyDateTime` helpers
> Not required
Closes https://github.com/taiga-family/maskito/issues/2002

feat(kit): new `maskitoParseDateTime` and `maskitoStringifyDateTime` helpers

---

projects/kit/src/index.ts
projects/kit/src/lib/masks/date-time/index.ts
projects/kit/src/lib/masks/date-time/utils/index.ts
projects/kit/src/lib/masks/date/index.ts
projects/kit/src/lib/masks/number/index.ts
projects/kit/src/lib/masks/time/index.ts

fix(kit): missing export of `maskitoParseDateTime` & `maskitoStringifyDateTime` utilities

---

projects/demo-integrations/src/tests/component-testing/react/change-event/change-event.cy.tsx
projects/demo/src/pages/frameworks/react/react-doc.template.html
projects/react/src/lib/adaptControlledElement.ts
projects/react/src/lib/tests/controlledInput.spec.tsx
projects/react/src/lib/tests/useMaskito.spec.tsx
projects/react/src/lib/useMaskito.ts

This PR solves 2 problems
```jsx
const options: MaskitoOptions = {
mask: /^[a-z]+$/i,
postprocessors: [({value, selection}) => ({selection, value: value.toUpperCase()})],
};
function App() {
const inputRef = useMaskito({options});
const [value, neverCalledFn] = useState('');
return (
<input
ref={inputRef}
value={value}
onInput={(e) => console.log(e.target.value)}
/>
);
}
```
**Expected behavior:** textfield value is always empty
**Actual behavior:** textfield value is updated on every keystroke
Learn more: https://react.dev/reference/react-dom/components/input#controlling-an-input-with-a-state-variable
<br />
```jsx
const options: MaskitoOptions = {
mask: /^[a-z]+$/i,
postprocessors: [({value, selection}) => ({selection, value: value.toUpperCase()})],
};
function App() {
const inputRef = …
```

feat(react): add support for React-specific `onChange` event handler

---

projects/core/src/lib/mask.ts
projects/core/src/lib/plugins/broken-prevent-default.plugin.ts
projects/core/src/lib/plugins/index.ts

Fixes #2135
Relates https://issues.chromium.org/issues/40885402

fix(core): Android with Microsoft SwiftKey Keyboard ignores `preventDefault()` for `beforeinput` event on backspace

---

projects/demo/src/pages/documentation/real-world-form/index.ts
projects/demo/src/pages/phone/phone-doc.component.ts

Hack with pattern works
https://github.com/user-attachments/assets/52f93d87-c637-45c7-b18c-1a51d2b87019
Hack is not working
https://github.com/user-attachments/assets/9241778f-f0d8-4190-850c-7f0177b54d80
Hack is not required
https://github.com/user-attachments/assets/5d83336a-8e07-4691-800c-04b45d95375d
___
<details>
<summary>Source code</summary>
```html
<form>
<input
autocomplete="tel"
inputmode="tel"
placeholder="Without pattern='+[0-9-]{1,20}'"
style="font-size: 23px;width: 100%;"
/>
<input
autocomplete="tel"
inputmode="tel"
pattern="+[0-9-]{1,20}"
placeholder="With pattern='+[0-9-]{1,20}'"
style="font-size: 23px;width: 100%;"
/>
</form>
<p id="logs"></p>
<script>
const inputs = document.querySelectorAll('input');
inputs.forEach(input => {
input.addEventListener('beforeinput', log); …
```

chore: deprecate safari hack

---

projects/demo-integrations/src/tests/kit/date-range/date-range-segments-zero-padding.cy.ts
projects/demo-integrations/src/tests/kit/date/date-segments-zero-padding.cy.ts
projects/kit/src/lib/utils/date/validate-date-string.ts

Fixed incorrect padding behavior logic and added corresponding tests to ensure proper functionality.
Fixes #2141

fix(kit): date-related mask with month-first mode has incorrect zero-padding logic

---

package.json

Library `highlight.js` fixed its bug with JSX.
This `overrides` is no more required
Explore body of this PR for more details:
* https://github.com/taiga-family/maskito/pull/738

chore: remove `overrides` for `highlight.js`

---

.eslintrc.js
package-lock.json
projects/core/src/lib/utils/test/pipe.spec.ts
projects/kit/src/lib/masks/number/utils/tests/to-number-parts.spec.ts

Relates:
* https://github.com/taiga-family/maskito/pull/2159
```
> eslint . --fix
/home/runner/work/maskito/maskito/projects/core/src/lib/classes/mask-model/tests/mask-model-fixed-characters.spec.ts
Error:    65:9  error  Tests should end with an assertion  jest/prefer-ending-with-an-expect
Error:    73:9  error  Tests should end with an assertion  jest/prefer-ending-with-an-expect
Error:    81:9  error  Tests should end with an assertion  jest/prefer-ending-with-an-expect
Error:    89:9  error  Tests should end with an assertion  jest/prefer-ending-with-an-expect
Error:    97:9  error  Tests should end with an assertion  jest/prefer-ending-with-an-expect
Error:   105:9  error  Tests should end with an assertion  jest/prefer-ending-with-an-expect …
```

ci: compatibility with `eslint-plugin-jest@28.13.0`

---

README.md

chore: fix size of Maskito logo in root `README.md`

---

projects/core/src/lib/mask.ts
projects/demo-integrations/src/tests/component-testing/native-max-length/native-maxlength-attribute.cy.ts
projects/demo-integrations/src/tests/component-testing/utils.ts

fix(kit): `Number` with `input[maxlength]` is incompatible with `document.execCommand('delete')`

---

projects/kit/src/lib/masks/date-range/constants.ts
projects/kit/src/lib/masks/date-range/processors/min-max-range-length-postprocessor.ts
projects/kit/src/lib/utils/date/append-date.ts
projects/kit/src/lib/utils/date/tests/append-date.spec.ts

fix(kit): `DateRange` + `minLength` / `maxLength` has incorrect limits
